-- shared_conformed.dim_date -- conformed calendar dimension
-- ECRMAP -- Ecosystem-Centric Real-World Multi-Domain Analytics Platform
-- Author: Sharique Mohammad
-- Date: September 2026
--
-- One row per calendar date. Ecosystem-independent -- no acquired-source
-- evidence is needed to populate this table, so it is fully populated
-- (see seed/dim_date.csv, generated by generate_seed.py).

CREATE TABLE shared_conformed.dim_date (
    date_key          integer      NOT NULL,   -- YYYYMMDD, surrogate + natural key
    calendar_date     date         NOT NULL,
    year              smallint     NOT NULL,
    quarter           smallint     NOT NULL,
    month             smallint     NOT NULL,
    month_name        varchar(20)  NOT NULL,
    day_of_month      smallint     NOT NULL,
    day_of_year        smallint    NOT NULL,
    iso_week           smallint    NOT NULL,
    day_of_week        smallint    NOT NULL,   -- ISO: 1=Monday .. 7=Sunday
    day_name           varchar(20) NOT NULL,
    is_weekend         boolean     NOT NULL,
    PRIMARY KEY (date_key)
);

CREATE UNIQUE INDEX ux_dim_date_calendar_date ON shared_conformed.dim_date (calendar_date);
