-- shared_conformed.dim_time -- conformed time-of-day dimension
-- ECRMAP -- Ecosystem-Centric Real-World Multi-Domain Analytics Platform
-- Author: Sharique Mohammad
-- Date: September 2026
--
-- One row per minute-of-day (0-1439). Ecosystem-independent -- no
-- acquired-source evidence is needed to populate this table, so it is fully
-- populated (see seed/dim_time.csv, generated by generate_seed.py).

CREATE TABLE shared_conformed.dim_time (
    time_key      smallint    NOT NULL,   -- 0..1439, minutes since midnight
    hour_24       smallint    NOT NULL,
    minute        smallint    NOT NULL,
    hour_12       smallint    NOT NULL,
    am_pm         varchar(2)  NOT NULL,
    quarter_hour  smallint    NOT NULL,   -- 0..3, which quarter of the hour
    daypart       varchar(20) NOT NULL,   -- night / morning / afternoon / evening
    PRIMARY KEY (time_key)
);
