# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# MAGIC %md
# MAGIC # EDA -- SEARCH VISIBILITY RELATIONSHIPS AND FINDINGS
# MAGIC
# MAGIC **Energy Commerce and Retail Media Analytics Platform**  
# MAGIC **Author:** Sharique Mohammad  
# MAGIC **Date:** August 2026
# MAGIC
# MAGIC **Purpose:** search_visibility_events <-> search_visibility_repository
# MAGIC joinability and referential integrity on repository_id, plus a findings
# MAGIC summary for src/schemas/profiling/search_visibility.md. The repository
# MAGIC table is small, so it is collected once and joined in Python.

# COMMAND ----------

# DBTITLE 1,Imports
import matplotlib.pyplot as plt
from pyspark.sql import DataFrame
from pyspark.sql import functions as F

import contextlib
import os as _os
import re as _re

# COMMAND ----------

# DBTITLE 1,Configuration
CATALOG = "energy_commerce_retail_media"
BRONZE_SCHEMA = "bronze"
SOURCE = "search_visibility"
NB_KEY = "02_relationships_and_findings"
SECTION_TITLE = "events <-> repository relationship (search_visibility)"
EVENTS = f"{CATALOG}.{BRONZE_SCHEMA}.search_visibility_events"
REPOSITORY = f"{CATALOG}.{BRONZE_SCHEMA}.search_visibility_repository"

# COMMAND ----------

# DBTITLE 1,Helper
def find_col(df: DataFrame, *candidates: str) -> str | None:
    lower = {c.lower(): c for c in df.columns}
    for cand in candidates:
        if cand.lower() in lower:
            return lower[cand.lower()]
    return None


def barplot(pairs, title, xlabel, ylabel="count", rot=0, filename=None):
    plt.figure(figsize=(9, 4))
    plt.bar([str(p[0]) for p in pairs], [p[1] for p in pairs])
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.xticks(rotation=rot, ha="right" if rot else "center")
    plt.tight_layout()
    if filename:
        plt.savefig(fig_path(filename), dpi=110, bbox_inches="tight")
    plt.show()


# COMMAND ----------

# DBTITLE 1,Profiling-export helper (writes src/schemas/profiling/<source>.md)
def _repo_root():
    p = _os.path.abspath(_os.getcwd())
    for _ in range(12):
        if _os.path.isdir(_os.path.join(p, "src", "schemas")) and _os.path.isdir(
            _os.path.join(p, "databricks", "eda")
        ):
            return p
        if _os.path.dirname(p) == p:
            break
        p = _os.path.dirname(p)
    with contextlib.suppress(Exception):
        wp = (
            dbutils.notebook.entry_point.getDbutils()
            .notebook()
            .getContext()
            .notebookPath()
            .get()
        )
        i = wp.rfind("/databricks/eda/")
        if i > 0:
            for cand in (wp[:i], "/Workspace" + wp[:i]):
                if _os.path.isdir(_os.path.join(cand, "src", "schemas")):
                    return cand
    raise RuntimeError(
        "repo root not found -- run from <repo>/databricks/eda/<source>/"
    )


def _profiling_dir():
    d = _os.path.join(_repo_root(), "src", "schemas", "profiling")
    _os.makedirs(_os.path.join(d, "figures"), exist_ok=True)
    return d


def fig_path(name):
    return _os.path.join(_profiling_dir(), "figures", name)


def write_profiling(source, notebook_key, section_title, blocks, figures=None):
    d = _profiling_dir()
    md = _os.path.join(d, source + ".md")
    lines = [f"<!-- BEGIN {source}:{notebook_key} -->", f"## {section_title}", ""]
    for heading, body in blocks:
        if body is None or str(body).strip() == "":
            continue
        lines += [f"### {heading}", "", str(body).rstrip(), ""]
    for cap, name in figures or []:
        lines += [f"### Figure -- {cap}", "", f"![{cap}](figures/{name})", ""]
    lines.append(f"<!-- END {source}:{notebook_key} -->")
    block = "\n".join(lines)
    existing = ""
    if _os.path.exists(md):
        with open(md, encoding="utf-8") as fh:
            existing = fh.read()
    pat = _re.compile(
        r"<!-- BEGIN "
        + _re.escape(source)
        + r":([\w.\-]+) -->.*?<!-- END "
        + _re.escape(source)
        + r":\1 -->",
        _re.DOTALL,
    )
    kept = {mm.group(1): mm.group(0) for mm in pat.finditer(existing)}
    kept[notebook_key] = block
    intro = f"_Auto-generated by the Phase 3 EDA notebooks (`databricks/eda/{source}/`). One `## ` section per notebook; re-running a notebook replaces its own section, other sections are preserved._"
    header = f"# {source.upper()} EDA PROFILE\n\n{intro}\n\n"
    body = "\n\n".join(kept[k] for k in sorted(kept))
    out = header + body + "\n"
    tmp = md + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(out)
    _os.replace(tmp, md)
    print(f"profiling export -> {md}  ('{notebook_key}', {len(kept)} section(s))")


# COMMAND ----------

# DBTITLE 1,Validate profiling export path
REPO_ROOT = _repo_root()
PROFILING_DIR = _profiling_dir()

print(f"OK  repo root: {REPO_ROOT}")
print(f"OK  profiling directory: {PROFILING_DIR}")

# COMMAND ----------

# DBTITLE 1,Repository table -- collect once, profile in Python
repo = spark.table(REPOSITORY)
repo_key = find_col(repo, "repository_id", "id", "repositoryId") or repo.columns[0]
repo_recs = [x.asDict() for x in repo.collect()]
repo_total = len(repo_recs)
repo_ids = {str(d[repo_key]) for d in repo_recs if d[repo_key] is not None}
repo_key_unique = repo_total == len(repo_ids)
print(
    f"repository rows={repo_total}  columns={repo.columns}  key={repo_key}  key_unique={repo_key_unique}"
)
for c in repo.columns:
    miss = sum(1 for d in repo_recs if d[c] is None or str(d[c]).strip() == "")
    print(f"  {c:<24} missing={miss}  distinct={len({d[c] for d in repo_recs})}")
for d in repo_recs[:100]:
    print("  ", d)

# COMMAND ----------

# DBTITLE 1,Events per repository_id + date coverage (one groupBy, collected)
events = spark.table(EVENTS)
evr = (
    events.groupBy(F.col("repository_id").cast("string").alias("repository_id"))
    .agg(
        F.count(F.lit(1)).alias("events"),
        F.countDistinct("date").alias("distinct_dates"),
        F.min("date").alias("first_date"),
        F.max("date").alias("last_date"),
    )
    .orderBy(F.desc("events"))
    .collect()
)
event_repo_ids = {x["repository_id"] for x in evr}
per_repo_pairs = [(x["repository_id"], x["events"]) for x in evr[:30]]
for x in evr[:50]:
    print(x.asDict())

# COMMAND ----------

# DBTITLE 1,Events summary + row-level match against the repository id set (one agg)
repo_id_list = list(repo_ids)
S = (
    events.agg(
        F.count(F.lit(1)).alias("ev_total"),
        F.approx_count_distinct("repository_id").alias("events_distinct_repo"),
        F.countDistinct("date").alias("overall_dates"),
        F.sum(
            F.col("repository_id").cast("string").isin(repo_id_list).cast("long")
        ).alias("matched_rows"),
    )
    .first()
    .asDict()
)
ev_total = S["ev_total"]
matched = S["matched_rows"]
overall_dates = S["overall_dates"]
orphan_events = len(event_repo_ids - repo_ids)
unused_repo = len(repo_ids - event_repo_ids)
kind = "1:N (one repository -> many events)" if repo_key_unique else "N:N"
partial = sum(1 for x in evr if x["distinct_dates"] < overall_dates)
print(
    f"events={ev_total}  distinct repository_id~={S['events_distinct_repo']}  matched rows={matched}  "
    f"unmatched rows={ev_total - matched}"
)
print(
    f"orphan event repository_ids (not in repository table)={orphan_events}  e.g. {sorted(event_repo_ids - repo_ids)[:20]}"
)
print(
    f"unused repository ids (never in events)={unused_repo}  e.g. {sorted(repo_ids - event_repo_ids)[:20]}"
)
print(f"events <-> repository cardinality: {kind}")
print(
    f"overall distinct dates={overall_dates}  repositories NOT present in every date={partial} of {len(event_repo_ids)}"
)

# COMMAND ----------

# DBTITLE 1,Figure -- coverage, integrity, events per repository
barplot(
    [(x["repository_id"], x["distinct_dates"]) for x in evr],
    "Search Visibility -- distinct dates per repository_id",
    "repository_id",
    "dates",
    rot=90,
    filename="sv_distinct_dates_per_repository.png",
)
barplot(
    [
        ("repository ids", len(repo_ids)),
        ("event repository_ids", len(event_repo_ids)),
        ("orphan events", orphan_events),
        ("unused repo rows", unused_repo),
    ],
    "Search Visibility -- repository_id coverage & integrity",
    "",
    "count",
    rot=30,
    filename="sv_repository_coverage_integrity.png",
)
barplot(
    per_repo_pairs,
    "Search Visibility -- events per repository_id (top 30)",
    "repository_id",
    "events",
    rot=90,
    filename="sv_events_per_repository.png",
)

# COMMAND ----------

# DBTITLE 1,Findings
print(
    f"repository rows={repo_total}  distinct ids={len(repo_ids)}  key_unique={repo_key_unique}"
)
print(
    f"events distinct repository_id~={S['events_distinct_repo']}  matched rows={matched}/{ev_total}"
)
print(f"orphan events={orphan_events}  unused repository rows={unused_repo}")
print(f"cardinality: {kind}  repositories missing months: {partial}")

# COMMAND ----------

# DBTITLE 1,Export profiling findings -> src/schemas/profiling/search_visibility.md
_entities = [
    (
        f"Repository table: rows={repo_total}, columns={repo.columns}, key=`{repo_key}`, "
        f"key_unique={repo_key_unique}, distinct ids={len(repo_ids)}."
    ),
    (
        f"Events table: rows={ev_total}, approx distinct repository_id={S['events_distinct_repo']}, "
        f"overall distinct dates={overall_dates}."
    ),
]

_rel = [
    f"events <-> repository cardinality on repository_id: {kind}.",
    (
        f"Row-level match of events against the repository id set: {matched} / {ev_total} "
        f"({matched / ev_total * 100:.2f}%) matched, {ev_total - matched} unmatched."
    ),
    (
        f"Orphan event repository_ids (not in repository table): {orphan_events} "
        f"(e.g. {sorted(event_repo_ids - repo_ids)[:20]})."
    ),
    (
        f"Unused repository ids (never referenced by events): {unused_repo} "
        f"(e.g. {sorted(repo_ids - event_repo_ids)[:20]})."
    ),
    f"Repositories not present in every date/month: {partial} of {len(event_repo_ids)}.",
]

_findings = []
if not repo_key_unique:
    _findings.append(
        f"- Repository key `{repo_key}` is NOT unique in the repository table."
    )
if orphan_events:
    _findings.append(
        f"- {orphan_events} event repository_ids have no matching repository row "
        f"({ev_total - matched} event rows affected) -- referential integrity is not enforced."
    )
if unused_repo:
    _findings.append(
        f"- {unused_repo} repository rows are never referenced by any event."
    )
if partial:
    _findings.append(f"- {partial} repositories have partial date/month coverage.")
if not _findings:
    _findings.append(
        "- events.repository_id is a clean foreign key into the repository table."
    )
_findings_md = "\n".join(_findings)

_silver = []
_silver.append(
    f"- Join events to repository on repository_id ({kind}); "
    + (
        "dedupe repository on the key first."
        if not repo_key_unique
        else "repository key is unique."
    )
)
if orphan_events:
    _silver.append(
        "- Use a left join and flag/quarantine events with an unresolved repository_id; "
        "do not drop them silently."
    )
if unused_repo:
    _silver.append(
        "- Unused repository rows are acceptable as a dimension; no action required."
    )

write_profiling(
    SOURCE,
    NB_KEY,
    SECTION_TITLE,
    [
        ("Entities / Keys", "\n".join(_entities)),
        ("Relationships", "\n".join(_rel)),
        ("EDA Findings", _findings_md),
        ("Silver Implications", "\n".join(_silver)),
    ],
    figures=[
        (
            "Search Visibility -- repository_id coverage & integrity",
            "sv_repository_coverage_integrity.png",
        ),
        (
            "Search Visibility -- events per repository_id (top 30)",
            "sv_events_per_repository.png",
        ),
    ],
)