# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# MAGIC %md
# MAGIC # GOLD INSPECTION LIBRARY
# MAGIC
# MAGIC **ECRMAP -- Ecosystem-Centric Real-World Multi-Domain Analytics Platform**
# MAGIC
# MAGIC **Author:** Sharique Mohammad
# MAGIC
# MAGIC **Date:** September 2026
# MAGIC
# MAGIC **Purpose:** the reusable post-Gold inspection framework, pulled into
# MAGIC every Gold notebook with `%run ../../_gold_inspect` after
# MAGIC `_silver_common` and `_gold_common`. Definitions only -- no side effects at
# MAGIC import; the caller owns `spark`. Every check is a small, bounded number of
# MAGIC aggregate passes, never a per-column scan loop -- the same performance
# MAGIC discipline as `_gold_common.py`.
# MAGIC
# MAGIC Same two-step shape as `_silver_inspect.py`: `inspect_gold_table()`
# MAGIC computes and returns findings, the calling notebook explicitly calls
# MAGIC `write_gold_findings()` itself (visible in the notebook, not hidden) to
# MAGIC write `src/schemas/gold_findings/<source>.md` -- a repo file, one `## `
# MAGIC section per notebook/table, re-run replaces its own section. No database
# MAGIC table involved.

# COMMAND ----------

# DBTITLE 1,Imports
import os as _os
import re as _re

from pyspark.sql import DataFrame
from pyspark.sql import functions as F

# COMMAND ----------

# DBTITLE 1,Configuration
# Columns skipped for approx_count_distinct -- expected-high-cardinality /
# free-text fields where a distinct count is not diagnostic and only adds cost.
HIGH_CARDINALITY_SKIP = {
    "source_record_id",
    "url",
    "page_location",
    "page_title",
    "search_term",
    "unique_search_term",
    "plant_name",
    "station_name",
    "offending_value",
}

# Boolean/status columns this framework recognises as DQ/trust flags by name.
_FLAG_COL_PATTERN = _re.compile(
    r"^_.*_(flag|violated|violation|outlier|suspected|ambiguous|out_of_set|conflict)$"
    r"|^is_[a-z_]+$"
    r"|_status$"
    r"|^currency_unknown$"
)

# COMMAND ----------

# DBTITLE 1,Findings export (src/schemas/gold_findings/<source>.md)
# Same mechanism as _silver_inspect.py's write_silver_findings -- a repo file,
# not just a table, so findings are readable the same way Silver's own
# findings docs are.


def _gold_findings_dir():
    d = _os.path.join(repo_root(), "src", "schemas", "gold_findings")
    _os.makedirs(d, exist_ok=True)
    return d


def write_gold_findings(
    source: str, notebook_key: str, section_title: str, blocks: list
) -> None:
    d = _gold_findings_dir()
    md = _os.path.join(d, source + ".md")
    lines = [f"<!-- BEGIN {source}:{notebook_key} -->", f"## {section_title}", ""]
    for heading, body in blocks:
        if body is None or str(body).strip() == "":
            continue
        lines += [f"### {heading}", "", str(body).rstrip(), ""]
    lines.append(f"<!-- END {source}:{notebook_key} -->")
    block = "\n".join(lines)
    existing = ""
    if _os.path.exists(md):
        with open(md, encoding="utf-8") as fh:
            existing = fh.read()
    pat = _re.compile(
        r"<!-- BEGIN "
        + _re.escape(source)
        + r":([\w.\-]+) -->.*?<!-- END "
        + _re.escape(source)
        + r":\1 -->",
        _re.DOTALL,
    )
    kept = {mm.group(1): mm.group(0) for mm in pat.finditer(existing)}
    kept[notebook_key] = block
    intro = (
        "_Auto-generated by the Gold notebooks (`databricks/gold/`). One "
        "`## ` section per (notebook, table); re-running a notebook replaces "
        "its own sections, other sections are preserved._"
    )
    header = f"# {source.upper()} GOLD FINDINGS\n\n{intro}\n\n"
    body_out = "\n\n".join(kept[k] for k in sorted(kept))
    out = header + body_out + "\n"
    tmp = md + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(out)
    _os.replace(tmp, md)
    print(f"findings export -> {md}  ('{notebook_key}', {len(kept)} section(s))")


def _findings_markdown(rows: list[tuple]) -> list:
    by_cat: dict[str, list] = {}
    for r in rows:
        cat, name = r[5], r[6]
        metric, obs, exp, status, sev, details = r[7], r[8], r[9], r[10], r[11], r[12]
        by_cat.setdefault(cat, []).append(
            (name, metric, obs, exp, status, sev, details)
        )
    blocks = []
    for cat in sorted(by_cat):
        table = [
            "| check | metric | observed | expected | status | severity | details |",
            "|---|---|---|---|---|---|---|",
        ]
        for name, metric, obs, exp, status, sev, details in by_cat[cat]:
            table.append(
                f"| {name} | {metric} | {obs if obs is not None else ''} | "
                f"{exp if exp is not None else ''} | {status} | {sev} | {details} |"
            )
        blocks.append((cat, "\n".join(table)))
    return blocks


# COMMAND ----------

# DBTITLE 1,Common inspection


def inspect_gold_table(
    df_after: DataFrame,
    gold_table: str,
    *,
    source: str,
    component: str,
    rid: str,
    schema: str | None = None,
    key_cols: list[str] | None = None,
    df_before: DataFrame | None = None,
    extra_checks: dict | None = None,
) -> list:
    """Run the common post-Gold checks on `df_after` and RETURN the findings
    as `blocks` ready for `write_gold_findings()` -- does not write anything
    itself. The caller writes explicitly:

        blocks = inspect_gold_table(df, TABLE, source=SOURCE, component=COMPONENT, rid=RID)
        write_gold_findings(SOURCE, f"{COMPONENT.split('/')[-1]}__{TABLE}", TABLE, blocks)

    `key_cols` -- the table's own grain key -- enables the duplicate/grain
    check; pair with `assert_unique_grain()` in `_gold_common.py` for the
    hard-fail version of the same check.
    `df_before` -- the Silver read this table was built from -- enables the
    input/output row-count reconciliation check; omit where not meaningful
    (a conformed dimension built from several Silver tables has no single
    1:1 counterpart).
    `extra_checks` -- {check_name: value} for domain-specific findings the
    caller already computed -- passed through as `transformation_specific`
    rows, never invented by this function.
    `schema` -- override the resolved `{ecosystem}_gold` schema (e.g. for a
    table published into `shared_conformed` via write_gold's own `schema=`).
    """
    ts = now_utc()
    rows: list[tuple] = []
    full = f"{CATALOG}.{schema or gold_schema_for(source)}.{gold_table}"
    cols = df_after.columns
    dtypes = dict(df_after.dtypes)

    def add(category, name, metric, observed, expected, status, severity, details=""):
        rows.append(
            (
                ts,
                rid,
                source,
                component,
                full,
                category,
                name,
                metric,
                None if observed is None else float(observed),
                None if expected is None else float(expected),
                status,
                severity,
                details,
            )
        )

    # Schema
    add("schema", "table_exists", "exists", 1.0, 1.0, "PASS", "INFO")
    add("schema", "column_count", "count", float(len(cols)), None, "INFO", "INFO")

    # Volume
    n_after = df_after.count()
    add("volume", "row_count", "rows", float(n_after), None, "INFO", "INFO")
    if df_before is not None:
        n_before = df_before.count()
        delta = n_after - n_before
        ratio = (n_after / n_before) if n_before else None
        vol_status = (
            "WARN" if (ratio is not None and (ratio < 0.5 or ratio > 2.0)) else "PASS"
        )
        add(
            "volume",
            "input_output_reconciliation",
            "row_delta",
            float(delta),
            float(n_before),
            vol_status,
            "WARN" if vol_status == "WARN" else "INFO",
            f"before={n_before} after={n_after}",
        )

    # Completeness (one agg pass across every column)
    if cols:
        null_exprs = [F.sum(F.col(c).isNull().cast("int")).alias(c) for c in cols]
        null_row = df_after.agg(*null_exprs).first()
        if null_row and n_after:
            for c in cols:
                rate = (null_row[c] or 0) / n_after
                add(
                    "completeness",
                    f"null_rate:{c}",
                    "null_rate",
                    rate,
                    None,
                    "INFO",
                    "INFO",
                )

    # Cardinality (one agg pass, skipping known-high-cardinality columns)
    card_cols = [c for c in cols if c not in HIGH_CARDINALITY_SKIP]
    if card_cols:
        card_exprs = [F.approx_count_distinct(F.col(c)).alias(c) for c in card_cols]
        card_row = df_after.agg(*card_exprs).first()
        for c in card_cols:
            add(
                "cardinality",
                f"distinct:{c}",
                "approx_distinct",
                float(card_row[c]),
                None,
                "INFO",
                "INFO",
            )

    # Grain / duplicate-key check (soft -- see assert_unique_grain for hard-fail)
    if key_cols:
        dup_n = df_after.groupBy(*key_cols).count().filter(F.col("count") > 1).count()
        grain_status = "WARN" if dup_n else "PASS"
        add(
            "grain",
            "duplicate_keys",
            "count",
            float(dup_n),
            0.0,
            grain_status,
            "WARN" if dup_n else "INFO",
            f"key_cols={key_cols}",
        )

    # Numeric behaviour (one agg pass over numeric columns)
    numeric_types = {"double", "float", "int", "bigint", "smallint", "decimal"}
    numeric_cols = [c for c in cols if dtypes.get(c) in numeric_types]
    if numeric_cols:
        stat_exprs = []
        for c in numeric_cols:
            stat_exprs += [
                F.min(c).alias(f"{c}__min"),
                F.max(c).alias(f"{c}__max"),
                F.sum((F.col(c) == 0).cast("int")).alias(f"{c}__zero"),
                F.sum((F.col(c) < 0).cast("int")).alias(f"{c}__neg"),
            ]
        stat_row = df_after.agg(*stat_exprs).first()
        for c in numeric_cols:
            add(
                "numeric",
                f"min:{c}",
                "min",
                stat_row[f"{c}__min"],
                None,
                "INFO",
                "INFO",
            )
            add(
                "numeric",
                f"max:{c}",
                "max",
                stat_row[f"{c}__max"],
                None,
                "INFO",
                "INFO",
            )
            add(
                "numeric",
                f"zero_count:{c}",
                "count",
                float(stat_row[f"{c}__zero"] or 0),
                None,
                "INFO",
                "INFO",
            )
            add(
                "numeric",
                f"negative_count:{c}",
                "count",
                float(stat_row[f"{c}__neg"] or 0),
                None,
                "INFO",
                "INFO",
            )

    # DQ / semantic-status flag counts (recognised by name, not forced on tables
    # that carry none)
    flag_cols = [c for c in cols if _FLAG_COL_PATTERN.search(c)]
    bool_flag_cols = [c for c in flag_cols if dtypes.get(c) == "boolean"]
    if bool_flag_cols:
        flag_exprs = [F.sum(F.col(c).cast("int")).alias(c) for c in bool_flag_cols]
        flag_row = df_after.agg(*flag_exprs).first()
        for c in bool_flag_cols:
            add(
                "dq",
                f"flag_true_count:{c}",
                "count",
                float(flag_row[c] or 0),
                None,
                "INFO",
                "INFO",
            )
    for c in flag_cols:
        if dtypes.get(c) == "string":
            vc = df_after.groupBy(c).count().collect()
            details = ", ".join(f"{r[c]}={r['count']}" for r in vc)
            add("dq", f"value_counts:{c}", "count", None, None, "INFO", "INFO", details)

    # Domain-specific checks the caller already computed -- never invented here
    if extra_checks:
        for name, value in extra_checks.items():
            numeric_value = (
                value
                if isinstance(value, (int, float)) and not isinstance(value, bool)
                else None
            )
            add(
                "transformation_specific",
                name,
                "value",
                numeric_value,
                None,
                "INFO",
                "INFO",
                str(value),
            )

    print(f"INSPECTED {full}: {len(rows)} check(s)")
    return _findings_markdown(rows)
