# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# MAGIC %md
# MAGIC # EDA -- KDD CUP 2012 TRACK 2 (CLICK PREDICTION)
# MAGIC
# MAGIC **Energy Commerce and Retail Media Analytics Platform**
# MAGIC **Author:** Sharique Mohammad
# MAGIC **Date:** August 2026
# MAGIC
# MAGIC **Purpose:** Profile kddcup2012_click_prediction (one Bronze table:
# MAGIC click / impression counts + ad / query / user id fields) -- schema,
# MAGIC missingness, constant columns, id-0 sentinel, class imbalance, id
# MAGIC cardinality & concentration, ad/query/user relationships, click
# MAGIC behaviour, duplicate-key (identical vs conflicting labels), CTR by
# MAGIC depth/position -- as evidence for Silver design. No timestamp column
# MAGIC exists in this dataset.

# COMMAND ----------

# DBTITLE 1,Imports
import contextlib
import os as _os
import re as _re

import matplotlib.pyplot as plt
from pyspark.sql import functions as F

# COMMAND ----------

# DBTITLE 1,Configuration
CATALOG = "energy_commerce_retail_media"
BRONZE_SCHEMA = "bronze"
SOURCE = "kddcup2012"
NB_KEY = "01_click_prediction"
SECTION_TITLE = "KDD Cup 2012 click prediction (kddcup2012_click_prediction)"
TABLE = f"{CATALOG}.{BRONZE_SCHEMA}.kddcup2012_click_prediction"
ID_COLS = [
    "url_hash",
    "ad_id",
    "advertiser_id",
    "query_id",
    "keyword_id",
    "title_id",
    "description_id",
    "user_id",
]
ZERO_SENTINEL = ["query_id", "keyword_id", "title_id", "description_id", "user_id"]

# COMMAND ----------


# DBTITLE 1,Helper
def barplot(pairs, title, xlabel, ylabel="rows", rot=0, filename=None):
    plt.figure(figsize=(10, 4))
    plt.bar([str(p[0]) for p in pairs], [p[1] for p in pairs])
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.xticks(rotation=rot, ha="right" if rot else "center")
    plt.tight_layout()
    if filename:
        plt.savefig(fig_path(filename), dpi=110, bbox_inches="tight")
    plt.show()


# COMMAND ----------


# DBTITLE 1,Profiling-export helper (writes src/schemas/profiling/<source>.md)
def _repo_root():
    p = _os.path.abspath(_os.getcwd())
    for _ in range(12):
        if _os.path.isdir(_os.path.join(p, "src", "schemas")) and _os.path.isdir(
            _os.path.join(p, "databricks", "eda")
        ):
            return p
        if _os.path.dirname(p) == p:
            break
        p = _os.path.dirname(p)
    with contextlib.suppress(Exception):
        wp = (
            dbutils.notebook.entry_point.getDbutils()
            .notebook()
            .getContext()
            .notebookPath()
            .get()
        )
        i = wp.rfind("/databricks/eda/")
        if i > 0:
            for cand in (wp[:i], "/Workspace" + wp[:i]):
                if _os.path.isdir(_os.path.join(cand, "src", "schemas")):
                    return cand
    raise RuntimeError(
        "repo root not found -- run from <repo>/databricks/eda/<source>/"
    )


def _profiling_dir():
    d = _os.path.join(_repo_root(), "src", "schemas", "profiling")
    _os.makedirs(_os.path.join(d, "figures"), exist_ok=True)
    return d


def fig_path(name):
    return _os.path.join(_profiling_dir(), "figures", name)


def fmt_pairs(pairs, n=25):
    # Render (label, value) pairs as markdown list lines, capped at n with a
    # "... (N more)" tail so the profiling .md never carries a 1000-row dump.
    items = list(pairs)
    out = [f"- {lbl}: {val}" for lbl, val in items[:n]]
    if len(items) > n:
        out.append(f"- ... ({len(items) - n} more)")
    return "\n".join(out)


def write_profiling(source, notebook_key, section_title, blocks, figures=None):
    d = _profiling_dir()
    md = _os.path.join(d, source + ".md")
    lines = [f"<!-- BEGIN {source}:{notebook_key} -->", f"## {section_title}", ""]
    for heading, body in blocks:
        if body is None or str(body).strip() == "":
            continue
        lines += [f"### {heading}", "", str(body).rstrip(), ""]
    for cap, name in figures or []:
        if not _os.path.exists(_os.path.join(d, "figures", name)):
            print(f"  profiling export: skipping absent figure {name}")
            continue
        lines += [f"### Figure -- {cap}", "", f"![{cap}](figures/{name})", ""]
    lines.append(f"<!-- END {source}:{notebook_key} -->")
    block = "\n".join(lines)
    existing = ""
    if _os.path.exists(md):
        with open(md, encoding="utf-8") as fh:
            existing = fh.read()
    pat = _re.compile(
        r"<!-- BEGIN "
        + _re.escape(source)
        + r":([\w.\-]+) -->.*?<!-- END "
        + _re.escape(source)
        + r":\1 -->",
        _re.DOTALL,
    )
    kept = {mm.group(1): mm.group(0) for mm in pat.finditer(existing)}
    kept[notebook_key] = block
    intro = f"_Auto-generated by the Phase 3 EDA notebooks (`databricks/eda/{source}/`). One `## ` section per notebook; re-running a notebook replaces its own section, other sections are preserved._"
    header = f"# {source.upper()} EDA PROFILE\n\n{intro}\n\n"
    body = "\n\n".join(kept[k] for k in sorted(kept))
    out = header + body + "\n"
    tmp = md + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(out)
    _os.replace(tmp, md)
    print(f"profiling export -> {md}  ('{notebook_key}', {len(kept)} section(s))")


# COMMAND ----------

# DBTITLE 1,Validate profiling export path
REPO_ROOT = _repo_root()
PROFILING_DIR = _profiling_dir()

print(f"OK  repo root: {REPO_ROOT}")
print(f"OK  profiling directory: {PROFILING_DIR}")

# COMMAND ----------

# DBTITLE 1,Profile -- rows, missingness, approx distinct, constant columns (one agg)
df = spark.table(TABLE)
COLS = df.columns
exprs = [F.count(F.lit(1)).alias("__rows")]
for c in COLS:
    miss = F.col(c).isNull() | (F.trim(F.col(c)) == "")
    exprs += [
        F.sum(miss.cast("long")).alias(c + "__m"),
        F.approx_count_distinct(c).alias(c + "__d"),
    ]
r = df.agg(*exprs).first().asDict()
total = r["__rows"]
id_card = {c: r[c + "__d"] for c in ID_COLS}
constant_cols = [c for c in COLS if r[c + "__d"] <= 1]
print(f"rows={total}  columns={len(COLS)}  ->  {COLS}")
for c in COLS:
    print(
        f"  {c:<16} missing={r[c + '__m']:>10} rate={r[c + '__m'] / total:.4f} approx_distinct={r[c + '__d']}"
    )
print("constant columns:", constant_cols)
df.show(10, truncate=False)
distinct_rows = df.distinct().count()
print("exact full-row duplicates:", total - distinct_rows)

# COMMAND ----------

# DBTITLE 1,Scalar summary -- CTR, class imbalance, validity, id-0 sentinel (one agg)
clk, imp = F.col("click").cast("double"), F.col("impression").cast("double")
agg = [
    F.sum(clk).alias("clicks"),
    F.sum(imp).alias("impressions"),
    F.sum((F.col("click").cast("int") > 0).cast("long")).alias("positive_rows"),
    F.sum((clk > imp).cast("long")).alias("click_gt_impr"),
    F.sum(
        (F.col("position").cast("int") > F.col("depth").cast("int")).cast("long")
    ).alias("pos_gt_depth"),
]
for c in ZERO_SENTINEL:
    agg.append(
        F.sum(((F.col(c) == "0") | (F.col(c) == 0)).cast("long")).alias(c + "__zero")
    )
S = df.agg(*agg).first().asDict()
pos = S["positive_rows"]
neg = total - pos
ctr = S["clicks"] / S["impressions"] if S["impressions"] else None
sentinel_zero = {c: S[c + "__zero"] for c in ZERO_SENTINEL}
print(f"clicks={S['clicks']}  impressions={S['impressions']}  CTR={ctr}")
print(
    f"class: positive={pos} ({pos / total:.4%})  negative={neg} ({neg / total:.4%})  "
    f"imbalance neg:pos = {neg / max(pos, 1):.1f}:1"
)
print(
    "invalid click>impression:",
    S["click_gt_impr"],
    " position>depth:",
    S["pos_gt_depth"],
)
print(
    "id-0 (unknown) rows:",
    {c: (n, round(n / total, 4)) for c, n in sentinel_zero.items()},
)

# COMMAND ----------

# DBTITLE 1,Small-domain distributions -- click / impression / depth / position + CTR (one groupBy)
g = (
    df.groupBy("click", "impression", "depth", "position")
    .agg(
        F.count(F.lit(1)).alias("n"), F.sum(F.col("click").cast("int")).alias("clicks")
    )
    .collect()
)


def marginal(field):
    acc = {}
    for x in g:
        acc[x[field]] = acc.get(x[field], 0) + x["n"]
    return sorted(acc.items())


def ctr_by(field):
    rows, clicks = {}, {}
    for x in g:
        rows[x[field]] = rows.get(x[field], 0) + x["n"]
        clicks[x[field]] = clicks.get(x[field], 0) + x["clicks"]
    return [(k, clicks[k] / rows[k] if rows[k] else None) for k in sorted(rows)]


clk_dist, imp_dist = marginal("click"), marginal("impression")
depth_dist, pos_dist = marginal("depth"), marginal("position")
ctr_depth, ctr_pos = ctr_by("depth"), ctr_by("position")
print("click:", clk_dist, " impression:", imp_dist)
print("depth:", depth_dist, " position:", pos_dist)
print("CTR by depth:", ctr_depth, " by position:", ctr_pos)

# COMMAND ----------

# DBTITLE 1,Duplicate-key -- same context, conflicting click labels (one groupBy)
CONTEXT = [c for c in COLS if c not in ("click", "impression")]
kg = df.groupBy(*CONTEXT).agg(
    F.count(F.lit(1)).alias("n"),
    F.countDistinct("click").alias("distinct_click"),
)
kb = (
    kg.agg(
        F.sum((F.col("n") > 1).cast("long")).alias("dup_keys"),
        F.sum(((F.col("n") > 1) & (F.col("distinct_click") > 1)).cast("long")).alias(
            "conflicting"
        ),
    )
    .first()
    .asDict()
)
print(
    f"context keys with >1 row: {kb['dup_keys']}  of which conflicting click labels: {kb['conflicting']}"
)
kg.where((F.col("n") > 1) & (F.col("distinct_click") > 1)).orderBy(F.desc("n")).limit(
    20
).show(truncate=False)

# COMMAND ----------

# DBTITLE 1,Entity relationships -- ads per advertiser, keywords/ads per query, etc.


def card(parent, *children):
    d = df.groupBy(parent).agg(*[F.approx_count_distinct(c).alias(c) for c in children])
    for c in children:
        s = (
            d.agg(F.min(c).alias("min"), F.max(c).alias("max"), F.avg(c).alias("avg"))
            .first()
            .asDict()
        )
        print(f"{parent} -> {c}: {'1:1' if s['max'] == 1 else '1:N'}  {s}")


card("advertiser_id", "ad_id")
card("ad_id", "advertiser_id")
card("query_id", "keyword_id", "ad_id")
card("user_id", "query_id")

# COMMAND ----------

# DBTITLE 1,Concentration -- top entities + their CTR (one groupBy per entity, bounded collect)
concentration = {}
top_counts = {}
for c in ("ad_id", "advertiser_id", "query_id", "user_id"):
    top = (
        df.groupBy(c)
        .agg(
            F.count(F.lit(1)).alias("rows"),
            F.avg(F.col("click").cast("double")).alias("ctr"),
        )
        .orderBy(F.desc("rows"))
        .limit(5000)
        .collect()
    )
    top_counts[c] = [x["rows"] for x in top]
    concentration[c] = {
        "approx_distinct": id_card[c],
        "top10_share": sum(x["rows"] for x in top[:10]) / total,
        "top50_share": sum(x["rows"] for x in top[:50]) / total,
    }
    print(f"--- {c} --- {concentration[c]}")
    for x in top[:10]:
        print(f"   {x[c]}  rows={x['rows']}  ctr={x['ctr']:.4f}")

# COMMAND ----------

# DBTITLE 1,Figures
barplot(
    [("click=0", neg), ("click>0", pos)],
    "KDD -- click class balance",
    "class",
    "rows",
    filename="kddcup2012_click_class_balance.png",
)
barplot(
    [(c, n / total) for c, n in sentinel_zero.items()],
    "KDD -- share of rows with id value 0 (unknown)",
    "column",
    "rate",
    rot=30,
    filename="kddcup2012_unknown_id_rate.png",
)
barplot(
    clk_dist,
    "KDD -- click value distribution",
    "click",
    "rows",
    filename="kddcup2012_click_distribution.png",
)
barplot(
    depth_dist,
    "KDD -- depth distribution",
    "depth",
    "rows",
    filename="kddcup2012_depth_distribution.png",
)
barplot(
    pos_dist,
    "KDD -- position distribution",
    "position",
    "rows",
    filename="kddcup2012_position_distribution.png",
)
barplot(
    ctr_depth,
    "KDD -- CTR by depth",
    "depth",
    "CTR",
    filename="kddcup2012_ctr_by_depth.png",
)
barplot(
    ctr_pos,
    "KDD -- CTR by position",
    "position",
    "CTR",
    filename="kddcup2012_ctr_by_position.png",
)
plt.figure(figsize=(10, 4))
plt.bar(list(id_card), list(id_card.values()), log=True)
plt.title("KDD -- distinct value count per id column")
plt.ylabel("distinct (log)")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.savefig(fig_path("kddcup2012_id_cardinality.png"), dpi=110, bbox_inches="tight")
plt.show()
for c in ("ad_id", "query_id", "user_id"):
    counts = top_counts[c]
    plt.figure(figsize=(9, 4))
    plt.loglog(range(1, len(counts) + 1), counts, marker=".", linestyle="none")
    plt.title(f"KDD -- rows per {c} (top 5000, log-log)")
    plt.xlabel("rank")
    plt.ylabel("rows")
    plt.tight_layout()
    plt.savefig(
        fig_path(f"kddcup2012_rows_per_{c}_loglog.png"), dpi=110, bbox_inches="tight"
    )
    plt.show()

# COMMAND ----------

# DBTITLE 1,Findings
print("constant columns:", constant_cols)
print(
    "id-0 (unknown) rates:", {c: round(n / total, 4) for c, n in sentinel_zero.items()}
)
print(f"class imbalance neg:pos = {neg / max(pos, 1):.1f}:1   overall CTR={ctr}")
print("context keys with conflicting click labels:", kb["conflicting"])
print("id cardinality (approx):", id_card)
print("concentration:", concentration)

# COMMAND ----------

# DBTITLE 1,Export profiling findings -> src/schemas/profiling/kddcup2012.md
_prof = ["| column | missing | rate | approx_distinct |", "|---|---|---|---|"]
for c in COLS:
    _prof.append(
        f"| {c} | {r[c + '__m']} | {r[c + '__m'] / total:.4f} | {r[c + '__d']} |"
    )
_prof += [
    "",
    (
        f"Rows: {total}. Columns: {COLS}. Constant columns: {constant_cols or 'none'}. "
        "No timestamp column exists in this dataset."
    ),
]

_dq = [
    f"Exact full-row duplicates: {total - distinct_rows}.",
    f"Invalid click>impression rows: {S['click_gt_impr']}.",
    f"Invalid position>depth rows: {S['pos_gt_depth']}.",
    (
        f"Context keys (all cols except click/impression) with >1 row: {kb['dup_keys']}, "
        f"of which conflicting click labels: {kb['conflicting']}."
    ),
    "",
    "id value 0 = 'unknown' sentinel, row counts:",
    "",
    "| column | zero rows | rate |",
    "|---|---|---|",
]
for c, n in sentinel_zero.items():
    _dq.append(f"| {c} | {n} | {n / total:.4f} |")

_entities = [
    "Approx distinct per id column:",
    "",
    "| column | approx_distinct |",
    "|---|---|",
]
for c, n in id_card.items():
    _entities.append(f"| {c} | {n} |")
_entities += [
    "",
    "Concentration (share of all rows held by the top entities):",
    "",
    "| entity | approx_distinct | top-10 share | top-50 share |",
    "|---|---|---|---|",
]
for c, x in concentration.items():
    _entities.append(
        f"| {c} | {x['approx_distinct']} | {x['top10_share']:.4f} | {x['top50_share']:.4f} |"
    )

_rel = [
    (
        "Entity relationship cardinalities (from approx_count_distinct of child per parent) "
        "are printed in the 'Entity relationships' cell; advertiser->ad and query->keyword/ad "
        "are 1:N, ad->advertiser is effectively 1:1."
    )
]

_dist = [
    f"Overall CTR (sum click / sum impression): {ctr}.",
    (
        f"Class balance: positive rows (click>0) = {pos} ({pos / total:.4%}), "
        f"negative = {neg} ({neg / total:.4%}); neg:pos imbalance = {neg / max(pos, 1):.1f}:1."
    ),
    "",
    f"click marginal: {clk_dist}",
    f"depth marginal: {depth_dist}",
    f"position marginal: {pos_dist}",
    "impression marginal (top 25 by row count):",
    fmt_pairs(sorted(imp_dist, key=lambda p: -p[1])),
    f"CTR by depth: {[(d_, round(v, 4) if v is not None else None) for d_, v in ctr_depth]}",
    f"CTR by position: {[(p_, round(v, 4) if v is not None else None) for p_, v in ctr_pos]}",
]

_findings = []
if constant_cols:
    _findings.append(f"- Constant columns: {constant_cols}.")
if total - distinct_rows:
    _findings.append(f"- {total - distinct_rows} exact duplicate rows.")
if kb["conflicting"]:
    _findings.append(
        f"- {kb['conflicting']} context keys carry conflicting click labels "
        "(same features, different outcome)."
    )
_hi_sent = {
    c: round(n / total, 4) for c, n in sentinel_zero.items() if n / total > 0.01
}
if _hi_sent:
    _findings.append(f"- Material 'unknown' (id=0) rates: {_hi_sent}.")
_findings.append(
    f"- Strong class imbalance ({neg / max(pos, 1):.1f}:1 negative:positive)."
)
if S["click_gt_impr"] or S["pos_gt_depth"]:
    _findings.append(
        f"- Logical violations present: click>impression={S['click_gt_impr']}, "
        f"position>depth={S['pos_gt_depth']}."
    )
_findings.append(
    "- CTR declines with position and varies with depth (position/depth are useful features)."
)
_findings_md = "\n".join(_findings)

_silver = []
if constant_cols:
    _silver.append(f"- Drop constant columns {constant_cols}.")
if total - distinct_rows:
    _silver.append("- Apply distinct on load to remove exact duplicate rows.")
if kb["conflicting"]:
    _silver.append(
        "- Conflicting-label context keys require a documented handling rule "
        "(keep both as observations, or aggregate to click-rate) before modelling."
    )
_silver.append(
    "- Treat id value 0 as NULL/unknown for query_id, keyword_id, title_id, "
    "description_id, user_id."
)
if S["click_gt_impr"] or S["pos_gt_depth"]:
    _silver.append(
        "- Flag or quarantine rows violating click<=impression and position<=depth."
    )
_silver.append(
    "- Silver grain: one row per ad impression event (context + click + impression)."
)

write_profiling(
    SOURCE,
    NB_KEY,
    SECTION_TITLE,
    [
        ("Profile", "\n".join(_prof)),
        ("Data Quality", "\n".join(_dq)),
        ("Entities / Keys", "\n".join(_entities)),
        ("Relationships", "\n".join(_rel)),
        ("Distributions", "\n".join(_dist)),
        ("EDA Findings", _findings_md),
        ("Silver Implications", "\n".join(_silver)),
    ],
    figures=[
        ("KDD -- click class balance", "kddcup2012_click_class_balance.png"),
        (
            "KDD -- share of rows with id value 0 (unknown)",
            "kddcup2012_unknown_id_rate.png",
        ),
        ("KDD -- CTR by depth", "kddcup2012_ctr_by_depth.png"),
        ("KDD -- CTR by position", "kddcup2012_ctr_by_position.png"),
        ("KDD -- distinct value count per id column", "kddcup2012_id_cardinality.png"),
        ("KDD -- click count distribution", "kddcup2012_click_distribution.png"),
        ("KDD -- depth distribution", "kddcup2012_depth_distribution.png"),
        ("KDD -- position distribution", "kddcup2012_position_distribution.png"),
        (
            "KDD -- rows per ad_id (log-log)",
            "kddcup2012_rows_per_ad_id_loglog.png",
        ),
        (
            "KDD -- rows per query_id (log-log)",
            "kddcup2012_rows_per_query_id_loglog.png",
        ),
        (
            "KDD -- rows per user_id (log-log)",
            "kddcup2012_rows_per_user_id_loglog.png",
        ),
    ],
)
