# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# MAGIC %md
# MAGIC # ANALYTICS INSPECTION LIBRARY
# MAGIC
# MAGIC **ECRMAP -- Ecosystem-Centric Real-World Multi-Domain Analytics Platform**
# MAGIC
# MAGIC **Author:** Sharique Mohammad
# MAGIC
# MAGIC **Date:** September 2026
# MAGIC
# MAGIC **Purpose:** the reusable post-Analytics inspection framework, pulled
# MAGIC into every Analytics notebook with `%run ../../_analytics_inspect` after
# MAGIC `_analytics_common`. Same two-step shape as `_gold_inspect.py`:
# MAGIC `inspect_analytics_table()` computes and returns findings, the calling
# MAGIC notebook explicitly calls `write_analytics_findings()` to write
# MAGIC `src/schemas/analytics_findings/<source>.md`.

# COMMAND ----------

# DBTITLE 1,Imports
import datetime as _dt
import os as _os
import re as _re

from pyspark.sql import DataFrame
from pyspark.sql import functions as F

# COMMAND ----------

# DBTITLE 1,Findings export (src/schemas/analytics_findings/<source>.md)


def _analytics_findings_dir():
    d = _os.path.join(repo_root(), "src", "schemas", "analytics_findings")
    _os.makedirs(d, exist_ok=True)
    return d


ANALYTICS_STALE_AFTER_HOURS = 24
_ANALYTICS_GEN_PAT = _re.compile(r"_Generated: (\d{4}-\d\d-\d\dT\d\d:\d\dZ)_")


def _mark_analytics_stale(block: str, now) -> str:
    if "> STALE" in block:
        return block
    m = _ANALYTICS_GEN_PAT.search(block)
    if m:
        gen = _dt.datetime.strptime(m.group(1), "%Y-%m-%dT%H:%MZ").replace(
            tzinfo=_dt.UTC
        )
        if now - gen <= _dt.timedelta(hours=ANALYTICS_STALE_AFTER_HOURS):
            return block
    head, _, rest = block.partition("\n## ")
    title, _, tail = rest.partition("\n")
    return (
        f"{head}\n## {title}\n\n"
        f"> STALE: not rewritten in the last {ANALYTICS_STALE_AFTER_HOURS}h\n{tail}"
    )


def write_analytics_findings(
    source: str, notebook_key: str, section_title: str, blocks: list
) -> None:
    d = _analytics_findings_dir()
    md = _os.path.join(d, source + ".md")
    now = _dt.datetime.now(tz=_dt.UTC)
    lines = [
        f"<!-- BEGIN {source}:{notebook_key} -->",
        f"## {section_title}",
        "",
        f"_Generated: {now.strftime('%Y-%m-%dT%H:%MZ')}_",
        "",
    ]
    for heading, body in blocks:
        if body is None or str(body).strip() == "":
            continue
        lines += [f"### {heading}", "", str(body).rstrip(), ""]
    lines.append(f"<!-- END {source}:{notebook_key} -->")
    block = "\n".join(lines)
    existing = ""
    if _os.path.exists(md):
        with open(md, encoding="utf-8") as fh:
            existing = fh.read()
    pat = _re.compile(
        r"<!-- BEGIN "
        + _re.escape(source)
        + r":([\w.\-]+) -->.*?<!-- END "
        + _re.escape(source)
        + r":\1 -->",
        _re.DOTALL,
    )
    kept = {
        mm.group(1): _mark_analytics_stale(mm.group(0), now)
        for mm in pat.finditer(existing)
    }
    kept[notebook_key] = block
    intro = (
        "_Auto-generated by the Analytics notebooks (`databricks/analytics/`). "
        "One `## ` section per (notebook, table); re-running a notebook "
        "replaces its own sections, other sections are preserved and marked "
        "STALE once older than 24h._"
    )
    header = f"# {source.upper()} ANALYTICS FINDINGS\n\n{intro}\n\n"
    body_out = "\n\n".join(kept[k] for k in sorted(kept))
    out = header + body_out + "\n"
    tmp = md + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(out)
    _os.replace(tmp, md)
    print(f"findings export -> {md}  ('{notebook_key}', {len(kept)} section(s))")


# COMMAND ----------

# DBTITLE 1,Common inspection


def inspect_analytics_table(
    df_after: DataFrame,
    table: str,
    *,
    source: str,
    component: str,
    rid: str,
    schema: str | None = None,
    key_cols: list[str] | None = None,
    df_before: DataFrame | None = None,
) -> list:
    """Same checks as Gold's inspect_gold_table() (schema, volume, grain,
    numeric), scoped to Analytics -- kept as one small pass rather than
    importing _gold_inspect.py's version, since the two stages report to
    different findings directories and audit component prefixes."""
    rows: list[tuple] = []
    full = f"{CATALOG}.{schema or analytics_schema_for(source)}.{table}"
    cols = df_after.columns

    def add(category, name, metric, observed, expected, status, severity, details=""):
        rows.append(
            (category, name, metric, observed, expected, status, severity, details)
        )

    add("schema", "table_exists", "exists", 1.0, 1.0, "PASS", "INFO")
    add("schema", "column_count", "count", float(len(cols)), None, "INFO", "INFO")

    n_after = df_after.count()
    add("volume", "row_count", "rows", float(n_after), None, "INFO", "INFO")
    if df_before is not None:
        # No ratio threshold here, unlike Gold's near-1:1 reshape check --
        # every Analytics mart is a deliberate grain-changing roll-up, so a
        # large row-count shrink is the expected outcome, not an anomaly.
        n_before = df_before.count()
        delta = n_after - n_before
        add(
            "volume",
            "input_output_reconciliation",
            "row_delta",
            float(delta),
            float(n_before),
            "INFO",
            "INFO",
            f"before={n_before} after={n_after}",
        )

    if key_cols:
        dup_n = df_after.groupBy(*key_cols).count().filter(F.col("count") > 1).count()
        add(
            "grain",
            "duplicate_keys",
            "count",
            float(dup_n),
            0.0,
            "PASS" if dup_n == 0 else "FAIL",
            "INFO" if dup_n == 0 else "CRITICAL",
            f"key_cols={key_cols}",
        )

    by_cat: dict[str, list] = {}
    for cat, name, metric, obs, exp, status, sev, details in rows:
        by_cat.setdefault(cat, []).append(
            (name, metric, obs, exp, status, sev, details)
        )
    blocks = []
    for cat in sorted(by_cat):
        table_md = [
            "| check | metric | observed | expected | status | severity | details |",
            "|---|---|---|---|---|---|---|",
        ]
        for name, metric, obs, exp, status, sev, details in by_cat[cat]:
            table_md.append(
                f"| {name} | {metric} | {obs if obs is not None else ''} | "
                f"{exp if exp is not None else ''} | {status} | {sev} | {details} |"
            )
        blocks.append((cat, "\n".join(table_md)))
    print(f"inspected {full}: {n_after} rows, {len(cols)} columns")
    return blocks
