# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# MAGIC %md
# MAGIC # ML INSPECTION LIBRARY
# MAGIC
# MAGIC **ECRMAP -- Ecosystem-Centric Real-World Multi-Domain Analytics Platform**
# MAGIC
# MAGIC **Author:** Sharique Mohammad
# MAGIC
# MAGIC **Date:** September 2026
# MAGIC
# MAGIC **Purpose:** the reusable post-build inspection framework, pulled into
# MAGIC every ML notebook with `%run ../../_ml_inspect` after `_ml_common`.
# MAGIC `inspect_ml_table()` computes findings, the calling notebook writes
# MAGIC `src/findings/ml_findings/<ecosystem>.md` with `write_ml_findings()`.

# COMMAND ----------

# DBTITLE 1,Imports
import datetime as _dt
import os as _os
import re as _re

from pyspark.sql import DataFrame
from pyspark.sql import functions as F

# COMMAND ----------

# DBTITLE 1,Findings export (src/findings/ml_findings/<source>.md)


def _ml_findings_dir():
    d = _os.path.join(repo_root(), "src", "findings", "ml_findings")
    _os.makedirs(d, exist_ok=True)
    return d


ML_STALE_AFTER_HOURS = 24
_ML_GEN_PAT = _re.compile(r"_Generated: (\d{4}-\d\d-\d\dT\d\d:\d\dZ)_")


def _mark_ml_stale(block: str, now) -> str:
    if "> STALE" in block:
        return block
    m = _ML_GEN_PAT.search(block)
    if m:
        gen = _dt.datetime.strptime(m.group(1), "%Y-%m-%dT%H:%MZ").replace(
            tzinfo=_dt.UTC
        )
        if now - gen <= _dt.timedelta(hours=ML_STALE_AFTER_HOURS):
            return block
    head, _, rest = block.partition("\n## ")
    title, _, tail = rest.partition("\n")
    return (
        f"{head}\n## {title}\n\n"
        f"> STALE: not rewritten in the last {ML_STALE_AFTER_HOURS}h\n{tail}"
    )


def write_ml_findings(
    source: str, notebook_key: str, section_title: str, blocks: list
) -> None:
    d = _ml_findings_dir()
    md = _os.path.join(d, source + ".md")
    now = _dt.datetime.now(tz=_dt.UTC)
    lines = [
        f"<!-- BEGIN {source}:{notebook_key} -->",
        f"## {section_title}",
        "",
        f"_Generated: {now.strftime('%Y-%m-%dT%H:%MZ')}_",
        "",
    ]
    for heading, body in blocks:
        if body is None or str(body).strip() == "":
            continue
        lines += [f"### {heading}", "", str(body).rstrip(), ""]
    lines.append(f"<!-- END {source}:{notebook_key} -->")
    block = "\n".join(lines)
    existing = ""
    if _os.path.exists(md):
        with open(md, encoding="utf-8") as fh:
            existing = fh.read()
    pat = _re.compile(
        r"<!-- BEGIN "
        + _re.escape(source)
        + r":([\w.\-]+) -->.*?<!-- END "
        + _re.escape(source)
        + r":\1 -->",
        _re.DOTALL,
    )
    kept = {
        mm.group(1): _mark_ml_stale(mm.group(0), now) for mm in pat.finditer(existing)
    }
    kept[notebook_key] = block
    intro = (
        "_Auto-generated by the ML notebooks (`databricks/ml/`). "
        "One `## ` section per (notebook, table); re-running a notebook "
        "replaces its own sections, other sections are preserved and marked "
        "STALE once older than 24h._"
    )
    header = f"# {source.upper()} ML FINDINGS\n\n{intro}\n\n"
    body_out = "\n\n".join(kept[k] for k in sorted(kept))
    out = header + body_out + "\n"
    tmp = md + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(out)
    _os.replace(tmp, md)
    print(f"findings export -> {md}  ('{notebook_key}', {len(kept)} section(s))")


# COMMAND ----------

# DBTITLE 1,Common inspection


def inspect_ml_table(
    df_after: DataFrame,
    table: str,
    *,
    ecosystem: str,
    key_cols: list[str] | None = None,
    df_before: DataFrame | None = None,
    partition_col: str | None = None,
    target_col: str | None = None,
) -> list:
    """Schema, volume, grain, per-column null rate, forbidden columns and, when
    the frame carries a partition, rows and target coverage per partition."""
    rows: list[tuple] = []
    full = ml_fqn(table, ecosystem)
    cols = df_after.columns

    def add(category, name, metric, observed, expected, status, severity, details=""):
        rows.append(
            (category, name, metric, observed, expected, status, severity, details)
        )

    add("schema", "column_count", "count", float(len(cols)), None, "INFO", "INFO")
    bad = [c for c in cols if c in CLASS_E_COLUMNS]
    add(
        "schema",
        "class_e_columns",
        "count",
        float(len(bad)),
        0.0,
        "PASS" if not bad else "FAIL",
        "INFO" if not bad else "CRITICAL",
        f"columns={bad}",
    )
    n_after = df_after.count()
    add("volume", "row_count", "rows", float(n_after), None, "INFO", "INFO")
    if df_before is not None:
        n_before = df_before.count()
        add(
            "volume",
            "input_output_reconciliation",
            "row_delta",
            float(n_after - n_before),
            float(n_before),
            "INFO",
            "INFO",
            f"before={n_before} after={n_after}",
        )
    if key_cols:
        dup_n = df_after.groupBy(*key_cols).count().filter(F.col("count") > 1).count()
        add(
            "grain",
            "duplicate_keys",
            "count",
            float(dup_n),
            0.0,
            "PASS" if dup_n == 0 else "FAIL",
            "INFO" if dup_n == 0 else "CRITICAL",
            f"key_cols={key_cols}",
        )
    rates = null_rates(df_after, cols)
    for c in cols:
        add(
            "completeness",
            f"null_rate:{c}",
            "null_rate",
            rates[c],
            None,
            "INFO",
            "INFO",
        )
    if partition_col and partition_col in cols:
        agg = [F.count("*").alias("n")]
        if target_col and target_col in cols:
            agg += [
                F.count(target_col).alias("target_n"),
                F.expr(f"avg(try_cast(`{target_col}` AS DOUBLE))").alias("target_mean"),
            ]
        for r in df_after.groupBy(partition_col).agg(*agg).collect():
            d = r.asDict()
            add(
                "partitions",
                f"partition:{d[partition_col]}",
                "rows",
                float(d["n"]),
                None,
                "INFO",
                "INFO",
                f"target_n={d.get('target_n')} target_mean={d.get('target_mean')}",
            )

    by_cat: dict[str, list] = {}
    for cat, name, metric, obs, exp, status, sev, details in rows:
        by_cat.setdefault(cat, []).append(
            (name, metric, obs, exp, status, sev, details)
        )
    blocks = []
    for cat in sorted(by_cat):
        table_md = [
            "| check | metric | observed | expected | status | severity | details |",
            "|---|---|---|---|---|---|---|",
        ]
        for name, metric, obs, exp, status, sev, details in by_cat[cat]:
            table_md.append(
                f"| {name} | {metric} | {obs if obs is not None else ''} | "
                f"{exp if exp is not None else ''} | {status} | {sev} | {details} |"
            )
        blocks.append((cat, "\n".join(table_md)))
    print(f"inspected {full}: {n_after} rows, {len(cols)} columns")
    return blocks


# COMMAND ----------

# DBTITLE 1,Markdown table helper


def markdown_table(headers: list[str], rows: list[tuple]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += [
        "| " + " | ".join("" if v is None else str(v) for v in r) + " |" for r in rows
    ]
    return "\n".join(lines)
