# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# MAGIC %md
# MAGIC # APPROVAL TEXT LIBRARY
# MAGIC
# MAGIC **ECRMAP -- Ecosystem-Centric Real-World Multi-Domain Analytics Platform**
# MAGIC
# MAGIC **Author:** Sharique Mohammad
# MAGIC
# MAGIC **Date:** October 2026
# MAGIC
# MAGIC **Purpose:** the approval findings text and the model card text, pulled in with
# MAGIC `%run ../lib/_approval_render` after `_model_common` and `_approval_rules`. Plain
# MAGIC Python, no Spark. Both texts are committed, so they pass through `scrub_private`.

# COMMAND ----------

# DBTITLE 1,Imports
import json as _json_text

# COMMAND ----------

# DBTITLE 1,Small helpers


def _loads(text, default):
    try:
        return _json_text.loads(text) if text else default
    except ValueError:
        return default


def _bullets(items) -> list:
    return [f"- {_cell(i, 400)}" for i in items] or ["- none"]


def _rule_ids(rules) -> str:
    return ", ".join(sorted({r["rule"] for r in rules})) or "none"


# COMMAND ----------

# DBTITLE 1,Approval findings text


def render_approval_findings(eco, rows, spec_rows, checks, stamp) -> str:
    """The decision record of one ecosystem as markdown."""
    lines = [
        f"# {eco.upper()} APPROVAL FINDINGS",
        "",
        (
            "_Auto-generated by `databricks/models/approve/gate/03_export_findings`. "
            "The decision belongs to the owner; a row decided by the rule engine "
            f"alone is a recommendation. Generated: {stamp}_"
        ),
        "",
        "## rules",
        "",
        markdown_table(
            ["rule", "class", "description", "parameter", "value"],
            [
                (
                    r["rule_id"],
                    r["rule_class"],
                    r["description"],
                    r["parameter"],
                    r["parameter_value"],
                )
                for r in sorted(spec_rows, key=lambda r: (r["rule_id"], r["parameter"]))
            ],
        ),
        "",
    ]
    chosen = [r for r in rows if r["role"] == "selected"]
    counts: dict = {}
    for r in chosen:
        key = (r["decision"], r["restriction"] or "")
        counts[key] = counts.get(key, 0) + 1
    lines += ["## summary", ""]
    lines.append(
        markdown_table(
            ["decision", "restriction", "tasks"],
            [(d, rs, n) for (d, rs), n in sorted(counts.items())],
        )
    )
    lines += ["", "## decisions", ""]
    lines.append(
        markdown_table(
            [
                "task",
                "model",
                "role",
                "decision",
                "restriction",
                "recommended",
                "overridden",
                "decided by",
                "rules",
            ],
            [
                (
                    r["task_id"],
                    r["model_name"],
                    r["role"],
                    r["decision"],
                    r["restriction"],
                    r["recommended_decision"],
                    r["overridden"],
                    r["decided_by"],
                    _rule_ids(_loads(r["rules"], [])),
                )
                for r in sorted(rows, key=lambda r: (r["task_id"], r["rank"]))
            ],
        )
    )
    overridden = [r for r in rows if r["overridden"]]
    lines += ["", "## overrides", ""]
    lines += [
        f"- {r['task_id']} / {r['model_name']}: {r['recommended_decision']} -> "
        f"{r['decision']}: {_cell(r['override_reason'], 300)}"
        for r in overridden
    ] or ["- none"]
    for r in sorted(chosen, key=lambda r: r["task_id"]):
        lines += ["", f"## {r['task_id']}", ""]
        lines.append(
            f"_model `{r['model_name']}`, decision `{r['decision']}`, restriction "
            f"`{r['restriction'] or 'none'}`, frozen version "
            f"{r['frozen_delta_version']}_"
        )
        lines += ["", "### rules", ""]
        lines.append(
            markdown_table(
                ["rule", "outcome", "detail"],
                [
                    (x["rule"], x["outcome"], x["detail"])
                    for x in _loads(r["rules"], [])
                ],
            )
        )
        lines += ["", "### conditions", ""] + _bullets(_loads(r["conditions"], []))
        segments = _loads(r["segments"], [])
        if segments:
            lines += ["", "### segments", ""]
            lines.append(
                markdown_table(
                    ["segment", "skill", "decision", "detail"],
                    [
                        (s["segment"], _number(s["skill"]), s["decision"], s["detail"])
                        for s in segments
                    ],
                )
            )
        notes = _loads(r["notes"], [])
        if notes:
            lines += ["", "### disclosures", ""] + _bullets(notes)
    lines += ["", "## check results", ""]
    lines.append(
        markdown_table(
            ["component", "check", "status", "detail", "recorded"],
            [
                (
                    c["component"],
                    c["metric_name"],
                    c["status"],
                    c["error_detail"],
                    c["recorded_at"],
                )
                for c in sorted(checks, key=lambda c: str(c["recorded_at"]))
            ],
        )
    )
    return scrub_private("\n".join(lines))


# COMMAND ----------

# DBTITLE 1,Facts for a card: data notes and library versions


def _read_note_lines(context_rows) -> list:
    ready = [
        r for r in context_rows or [] if r["status"] == "data_ready" and r["data_notes"]
    ]
    if not ready:
        return ["- not recorded"]
    out = []
    for note in _loads(ready[-1]["data_notes"], []):
        read = note.get("read")
        if read:
            shown = ", ".join(f"{k} {v}" for k, v in read.items())
            out.append(f"- held-out read: {shown}")
        elif "rows" in note:
            out.append(
                f"- frame: {note.get('rows')} rows, columns {note.get('columns')}, "
                f"rows by partition {note.get('rows_by_partition')}"
            )
    return out or ["- not recorded"]


def _library_line(fit_rows) -> str:
    rows = [r for r in fit_rows or [] if r["library_versions"]]
    if not rows:
        return "not recorded"
    last = max(rows, key=lambda r: str(r["recorded_at"]))
    versions = _loads(last["library_versions"], {})
    return ", ".join(f"{k} {v}" for k, v in sorted(versions.items()) if v != "missing")


# COMMAND ----------

# DBTITLE 1,Model card text


def _metric_table(selected, baseline, results) -> str:
    def values(model):
        return {
            r["metric"]: (r["value"], r["validation_value"])
            for r in results
            if r["model_name"] == model and r["metric"] and "__" not in r["metric"]
        }

    mine = values(selected["model_name"])
    base = values(baseline["model_name"])
    rows = [
        (
            name,
            _number(mine[name][0]),
            _number(mine[name][1]),
            _number(base.get(name, (None, None))[0]),
        )
        for name in sorted(mine)
    ]
    heads = [
        "metric",
        f"{selected['model_name']} held-out",
        f"{selected['model_name']} validation",
        f"{baseline['model_name']} held-out",
    ]
    return markdown_table(heads, rows)


def render_model_card(task, selected, baseline, facts, spec, stamp) -> str:
    """One card for an approved model, with its baseline fallback. `facts` holds
    results, flags, eval_context, fit_context, params and extra lines."""
    rules = _loads(selected["rules"], [])
    conditions = _loads(selected["conditions"], [])
    segments = _loads(selected["segments"], [])
    notes = _loads(selected["notes"], [])
    limit = spec["degradation_relative"]
    override = f"yes, {selected['override_reason']}" if selected["overridden"] else "no"
    lines = [
        f"# Model card: {task['task_id']}",
        "",
        (
            f"_model `{selected['model_name']}`, dataset `{task['dataset_id']}`, "
            f"frozen version {selected['frozen_delta_version']}, primary metric "
            f"`{task['primary_metric']}` "
            f"({'higher' if task['higher_is_better'] else 'lower'} is better). "
            f"Generated: {stamp}_"
        ),
        "",
        "## Decision",
        "",
        f"- decision: `{selected['decision']}`",
        f"- restriction: `{selected['restriction'] or 'none'}`",
        f"- recommended by the rules: `{selected['recommended_decision']}`",
        f"- overridden by the owner: {override}",
        f"- decided by: {selected['decided_by']}",
        f"- rules applied: {_rule_ids(rules)}",
        "",
        "## Purpose and task",
        "",
        f"- paradigm: {task['paradigm']}; task type: {task['task_type']}",
        f"- target: `{task['target']}`",
        f"- baseline fallback: `{baseline['model_name']}`",
        "",
        "## Intended use",
        "",
        (
            f"- estimates `{task['target']}` for the entities and period of "
            f"dataset `{task['dataset_id']}`"
        ),
        "- comparison and analysis with the stated conditions below",
        "",
        "## Out of scope",
        "",
        "- use on entities, periods or ecosystems outside the frozen dataset",
        "- operational use of a model restricted to offline or diagnostic use",
        "- registration, versioning and serving are separate steps",
        "",
        "## Data",
        "",
        *_read_note_lines(facts.get("eval_context")),
        *facts.get("extra", []),
        "",
        "## Training",
        "",
        (
            f"- model family: {selected['model_name']}; MLflow run "
            f"`{selected['mlflow_run_id']}`"
        ),
        f"- parameters: {_cell(facts.get('params'), 600) or 'not recorded'}",
        f"- library versions: {_library_line(facts.get('fit_context'))}",
        "- processor type: not recorded for the training and evaluation runs",
        "",
        "## Metrics",
        "",
        _metric_table(selected, baseline, facts["results"]),
    ]
    if segments:
        lines += ["", "## Segments", ""]
        lines.append(
            markdown_table(
                ["segment", "skill", "decision", "detail"],
                [
                    (s["segment"], _number(s["skill"]), s["decision"], s["detail"])
                    for s in segments
                ],
            )
        )
    flags = facts.get("flags") or []
    lines += ["", "## Flags", ""]
    lines += _bullets(f"{f['flag']}: {f['detail']}" for f in flags)
    lines += ["", "## Conditions and known limits", ""] + _bullets(conditions)
    lines += ["", "## Disclosures", ""] + _bullets(notes)
    lines += [
        "",
        "## Revalidation trigger",
        "",
        (
            "- a new frozen dataset version, or error on newer data more than "
            f"{limit:.0%} above the validation error"
        ),
        "",
        "## Baseline fallback",
        "",
        (
            f"- `{baseline['model_name']}`: validation "
            f"{_number(baseline['validation_value'])}, held-out "
            f"{_number(baseline['evaluated_value'])} on `{task['primary_metric']}`"
        ),
    ]
    return scrub_private("\n".join(lines))
