# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# MAGIC %md
# MAGIC # APPROVAL TEXT LIBRARY
# MAGIC
# MAGIC **ECRMAP -- Ecosystem-Centric Real-World Multi-Domain Analytics Platform**
# MAGIC
# MAGIC **Author:** Sharique Mohammad
# MAGIC
# MAGIC **Date:** October 2026
# MAGIC
# MAGIC **Purpose:** the approval findings text and the model card text, pulled in with
# MAGIC `%run ../lib/_approval_render` after `_model_common` and `_approval_rules`. Plain
# MAGIC Python, no Spark. Both texts are committed, so they pass through `scrub_private`.

# COMMAND ----------

# DBTITLE 1,Imports
import json as _json_text

# COMMAND ----------

# DBTITLE 1,Small helpers


def _loads(text, default):
    try:
        return _json_text.loads(text) if text else default
    except ValueError:
        return default


# a check recorded per ecosystem carries the ecosystem after a colon
_OTHER_ECOSYSTEM_SUFFIX = {"energy": ":commerce", "commerce": ":energy"}


def _bullets(items) -> list:
    return [f"- {_cell(i, 400)}" for i in items] or ["- none"]


def _rule_ids(rules) -> str:
    return ", ".join(sorted({r["rule"] for r in rules})) or "none"


# COMMAND ----------

# DBTITLE 1,Approval findings text


def render_approval_findings(eco, rows, spec_rows, checks, stamp) -> str:
    """The decision record of one ecosystem as markdown."""
    lines = [
        f"# {eco.upper()} APPROVAL FINDINGS",
        "",
        (
            "_Auto-generated by `databricks/models/approve/gate/03_export_findings`. "
            "The decision belongs to the owner; a row decided by the rule engine "
            f"alone is a recommendation. Generated: {stamp}_"
        ),
        "",
        "## rules",
        "",
        markdown_table(
            ["rule", "class", "description", "parameter", "value"],
            [
                (
                    r["rule_id"],
                    r["rule_class"],
                    r["description"],
                    r["parameter"],
                    r["parameter_value"],
                )
                for r in sorted(spec_rows, key=lambda r: (r["rule_id"], r["parameter"]))
            ],
        ),
        "",
    ]
    chosen = [r for r in rows if r["role"] == "selected"]
    counts: dict = {}
    for r in chosen:
        key = (r["decision"], r["restriction"] or "")
        counts[key] = counts.get(key, 0) + 1
    lines += ["## summary", ""]
    lines.append(
        markdown_table(
            ["decision", "restriction", "tasks"],
            [(d, rs, n) for (d, rs), n in sorted(counts.items())],
        )
    )
    lines += ["", "## decisions", ""]
    lines.append(
        markdown_table(
            [
                "task",
                "model",
                "role",
                "decision",
                "restriction",
                "recommended",
                "overridden",
                "decided by",
                "rules",
            ],
            [
                (
                    r["task_id"],
                    r["model_name"],
                    r["role"],
                    r["decision"],
                    r["restriction"],
                    r["recommended_decision"],
                    r["overridden"],
                    r["decided_by"],
                    _rule_ids(_loads(r["rules"], [])),
                )
                for r in sorted(rows, key=lambda r: (r["task_id"], r["rank"]))
            ],
        )
    )
    overridden = [r for r in rows if r["overridden"]]
    lines += ["", "## overrides", ""]
    lines += [
        f"- {r['task_id']} / {r['model_name']}: {r['recommended_decision']} -> "
        f"{r['decision']}: {_cell(r['override_reason'], 300)}"
        for r in overridden
    ] or ["- none"]
    for r in sorted(chosen, key=lambda r: r["task_id"]):
        lines += ["", f"## {r['task_id']}", ""]
        lines.append(
            f"_model `{r['model_name']}`, decision `{r['decision']}`, restriction "
            f"`{r['restriction'] or 'none'}`, frozen version "
            f"{r['frozen_delta_version']}_"
        )
        lines += ["", "### rules", ""]
        lines.append(
            markdown_table(
                ["rule", "outcome", "detail"],
                [
                    (x["rule"], x["outcome"], x["detail"])
                    for x in _loads(r["rules"], [])
                ],
            )
        )
        lines += ["", "### conditions", ""] + _bullets(_loads(r["conditions"], []))
        segments = _loads(r["segments"], [])
        if segments:
            lines += ["", "### segments", ""]
            lines.append(
                markdown_table(
                    ["segment", "skill", "decision", "detail"],
                    [
                        (s["segment"], _number(s["skill"]), s["decision"], s["detail"])
                        for s in segments
                    ],
                )
            )
        notes = _loads(r["notes"], [])
        if notes:
            lines += ["", "### disclosures", ""] + _bullets(notes)
    lines += ["", "## check results", ""]
    lines.append(
        markdown_table(
            ["component", "check", "status", "detail", "recorded"],
            [
                (
                    c["component"],
                    c["metric_name"],
                    c["status"],
                    c["error_detail"],
                    c["recorded_at"],
                )
                for c in sorted(checks, key=lambda c: str(c["recorded_at"]))
                if not c["metric_name"].endswith(_OTHER_ECOSYSTEM_SUFFIX[eco])
            ],
        )
    )
    return scrub_private("\n".join(lines))


# COMMAND ----------

# DBTITLE 1,Card constants
INTERNAL_METRIC_PREFIXES = ("bootstrap_", "pred_", "reproduc")
# libraries a model needs; the run records every installed library
MODEL_LIBRARIES = {
    "logistic": ("sklearn",),
    "gbt_sklearn": ("sklearn",),
    "poisson_gbt_sklearn": ("sklearn",),
    "forecast_residual_sklearn": ("sklearn",),
    "reward_weighted_gbt_sklearn": ("sklearn",),
    "gbt_lightgbm": ("lightgbm",),
    "gbt_cross_variable_lightgbm": ("lightgbm",),
    "quantile_gbt_lightgbm": ("lightgbm",),
    "survival_forest": ("sksurv",),
    "conservative_q": ("torch",),
    "sequence_gru": ("torch",),
    "sequence_transformer": ("torch",),
    "label_model": (),
}
INTENDED_USE = {
    "price_daily.price": "estimates the daily electricity price in EUR per MWh",
    "price_quarter_hour.price": (
        "estimates the quarter-hour electricity price in EUR per MWh"
    ),
    "price_quarter_hour.negative_price": (
        "estimates the probability that a quarter-hour has a negative electricity price"
    ),
    "load.load": "estimates the electricity load in MWh",
    "bias.bias": (
        "estimates the bias of the published generation forecast in MWh, per forecast scope"
    ),
    "zone_generation.generation": ("estimates the generation in MWh of a control zone"),
    "honda_forecast.increment": (
        "estimates the next energy increment of a Honda site channel"
    ),
    "honda_anomaly.anomaly": (
        "scores Honda site energy readings for anomalies; the evidence rests on "
        "injected anomalies"
    ),
    "ccpp.output": (
        "estimates the net electrical output in MW of a combined cycle power plant "
        "from its operating conditions"
    ),
    "capacity_additions.additions": ("estimates the capacity in MW added per period"),
    "redispatch.any_event": (
        "estimates the probability that a redispatch event occurs"
    ),
    "redispatch.event_energy": (
        "estimates the logarithm of the energy of a redispatch event in MWh"
    ),
    "survival.unit_lifetime": (
        "estimates the lifetime in years of a generation unit and its probability "
        "of still being in operation after 1, 3 and 5 years"
    ),
    "redispatch_matching.tier": (
        "predicts the match tier of a redispatch plant name against the registered units"
    ),
    "weak_supervision.labels": (
        "combines labelling functions into one label; there is no ground truth"
    ),
    "weather_imputation.reconstruction": (
        "fills missing weather values, per weather variable"
    ),
    "self_supervised_other.reconstruction": (
        "reconstructs masked or shifted values of the energy series"
    ),
    "rl_pumped_storage.policy": (
        "proposes the net pumped-storage action in MWh; evaluated on logged data only"
    ),
    "rl_redispatch.policy": (
        "proposes the direction of a redispatch action; evaluated on logged data only"
    ),
    "session_purchase_ga4.purchase": (
        "estimates the probability that a GA4 session ends in a purchase, from "
        "the first events of the session"
    ),
    "session_purchase_rees46.purchase": (
        "estimates the probability that a REES46 session ends in a purchase, from "
        "the first events of the session"
    ),
    "lapse_ga4.return": "estimates the probability that a GA4 user returns",
    "lapse_rees46.return": "estimates the probability that a REES46 user returns",
    "next_item_ga4.next_item": (
        "ranks products by the probability of being the next product in a GA4 session"
    ),
    "next_item_rees46.next_item": (
        "ranks products by the probability of being the next product in a REES46 session"
    ),
    "rl_session_sequences.policy": (
        "proposes the next event type of a session; evaluated on logged data only"
    ),
}

# COMMAND ----------

# DBTITLE 1,Facts for a card: data notes and library versions


def _read_note_lines(context_rows) -> list:
    ready = [
        r for r in context_rows or [] if r["status"] == "data_ready" and r["data_notes"]
    ]
    if not ready:
        return ["- not recorded"]
    out = []
    for note in _loads(ready[-1]["data_notes"], []):
        read = note.get("read")
        if read:
            shown = ", ".join(f"{k} {v}" for k, v in read.items())
            out.append(f"- held-out read: {shown}")
        elif "rows" in note:
            out.append(
                f"- frame: {note.get('rows')} rows, columns {note.get('columns')}, "
                f"rows by partition {note.get('rows_by_partition')}"
            )
    return out or ["- not recorded"]


def _library_line(fit_rows, model_name) -> str:
    needed = MODEL_LIBRARIES.get(model_name)
    rows = [r for r in fit_rows or [] if r["library_versions"]]
    if needed is None or not rows:
        return "not recorded"
    if not needed:
        return "none beyond the standard numerical stack"
    last = max(rows, key=lambda r: str(r["recorded_at"]))
    versions = _loads(last["library_versions"], {})
    shown = [
        f"{k} {versions[k]}" for k in needed if versions.get(k, "missing") != "missing"
    ]
    return ", ".join(shown) or "not recorded"


# COMMAND ----------

# DBTITLE 1,Model card text


def _metric_table(selected, baseline, results) -> str:
    def values(model):
        return {
            r["metric"]: (r["value"], r["validation_value"])
            for r in results
            if r["model_name"] == model
            and r["metric"]
            and "__" not in r["metric"]
            and not r["metric"].startswith(INTERNAL_METRIC_PREFIXES)
        }

    mine = values(selected["model_name"])
    base = values(baseline["model_name"])
    rows = [
        (
            name,
            _number(mine[name][0]),
            _number(mine[name][1]),
            _number(base.get(name, (None, None))[0]),
        )
        for name in sorted(mine)
    ]
    heads = [
        "metric",
        f"{selected['model_name']} held-out",
        f"{selected['model_name']} validation",
        f"{baseline['model_name']} held-out",
    ]
    return markdown_table(heads, rows)


def _intended_use_lines(task, selected) -> list:
    text = INTENDED_USE.get(task["task_id"])
    if text is None:
        return [f"- estimates `{task['target']}` on dataset `{task['dataset_id']}`"]
    lines = [
        f"- {text}",
        f"- target `{task['target']}`, dataset `{task['dataset_id']}`",
    ]
    if selected["restriction"]:
        lines.append(
            f"- restricted to {selected['restriction'].replace('_', ' ')} "
            "(see the conditions below)"
        )
    return lines


def render_model_card(task, selected, baseline, facts, spec, stamp) -> str:
    """One card for an approved model, with its baseline fallback. `facts` holds
    results, flags, eval_context, fit_context, params and extra lines."""
    rules = _loads(selected["rules"], [])
    conditions = _loads(selected["conditions"], [])
    segments = _loads(selected["segments"], [])
    notes = _loads(selected["notes"], [])
    limit = spec["degradation_relative"]
    override = f"yes, {selected['override_reason']}" if selected["overridden"] else "no"
    lines = [
        f"# Model card: {task['task_id']}",
        "",
        (
            f"_model `{selected['model_name']}`, dataset `{task['dataset_id']}`, "
            f"frozen version {selected['frozen_delta_version']}, primary metric "
            f"`{task['primary_metric']}` "
            f"({'higher' if task['higher_is_better'] else 'lower'} is better). "
            f"Generated: {stamp}_"
        ),
        "",
        "## Decision",
        "",
        f"- decision: `{selected['decision']}`",
        f"- restriction: `{selected['restriction'] or 'none'}`",
        f"- recommended by the rules: `{selected['recommended_decision']}`",
        f"- overridden by the owner: {override}",
        f"- decided by: {selected['decided_by']}",
        f"- rules applied: {_rule_ids(rules)}",
        "",
        "## Purpose and task",
        "",
        f"- paradigm: {task['paradigm']}; task type: {task['task_type']}",
        f"- target: `{task['target']}`",
        f"- baseline fallback: `{baseline['model_name']}`",
        "",
        "## Intended use",
        "",
        *_intended_use_lines(task, selected),
        "",
        "## Out of scope",
        "",
        "- use on entities, periods or ecosystems outside the frozen dataset",
        "- operational use of a model restricted to offline or diagnostic use",
        "- registration, versioning and serving are separate steps",
        "",
        "## Data",
        "",
        *_read_note_lines(facts.get("eval_context")),
        *facts.get("extra", []),
        "",
        "## Training",
        "",
        (
            f"- model family: {selected['model_name']}; MLflow run "
            f"`{selected['mlflow_run_id']}`"
        ),
        f"- parameters: {_cell(facts.get('params'), 600) or 'not recorded'}",
        f"- library versions: {_library_line(facts.get('fit_context'), selected['model_name'])}",
        "- processor type: not recorded for the training and evaluation runs",
        "",
        "## Metrics",
        "",
        _metric_table(selected, baseline, facts["results"]),
    ]
    if segments:
        lines += ["", "## Segments", ""]
        lines.append(
            markdown_table(
                ["segment", "skill", "decision", "detail"],
                [
                    (s["segment"], _number(s["skill"]), s["decision"], s["detail"])
                    for s in segments
                ],
            )
        )
    flags = facts.get("flags") or []
    lines += ["", "## Flags", ""]
    lines += _bullets(f"{f['flag']}: {f['detail']}" for f in flags)
    lines += ["", "## Conditions and known limits", ""] + _bullets(conditions)
    lines += ["", "## Disclosures", ""] + _bullets(notes)
    lines += [
        "",
        "## Revalidation trigger",
        "",
        (
            "- a new frozen dataset version, or error on newer data more than "
            f"{limit:.0%} above the validation error"
        ),
        "",
        "## Baseline fallback",
        "",
        (
            f"- `{baseline['model_name']}`: validation "
            f"{_number(baseline['validation_value'])}, held-out "
            f"{_number(baseline['evaluated_value'])} on `{task['primary_metric']}`"
        ),
    ]
    return scrub_private("\n".join(lines))
