# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# MAGIC %md
# MAGIC # EDA -- IPINYOU REFERENCE
# MAGIC
# MAGIC **Energy Commerce and Retail Media Analytics Platform**
# MAGIC **Author:** Sharique Mohammad
# MAGIC **Date:** August 2026
# MAGIC
# MAGIC **Purpose:** Profile ipinyou_reference (the merged city / region /
# MAGIC user_profile_tags lookup, discriminated by lookup_type) -- schema,
# MAGIC per-type row counts, lookup_id uniqueness & contiguity within type,
# MAGIC name_en / name_cn completeness -- as evidence for Silver design and the
# MAGIC referential-integrity checks in notebook 03. This table is small, so
# MAGIC it is collected once and analysed in Python.

# COMMAND ----------

# DBTITLE 1,Imports
import contextlib
import os as _os
import re as _re

import matplotlib.pyplot as plt
import numpy as np
from pyspark.sql import functions as F

# COMMAND ----------

# DBTITLE 1,Configuration
CATALOG = "energy_commerce_retail_media"
BRONZE_SCHEMA = "bronze"
SOURCE = "ipinyou"
NB_KEY = "02_reference"
SECTION_TITLE = "Reference lookup table (ipinyou_reference)"
TABLE = f"{CATALOG}.{BRONZE_SCHEMA}.ipinyou_reference"

# COMMAND ----------


# DBTITLE 1,Helper
def barplot(pairs, title, xlabel, ylabel="rows", rot=0, filename=None):
    plt.figure(figsize=(9, 4))
    plt.bar([str(p[0]) for p in pairs], [p[1] for p in pairs])
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.xticks(rotation=rot, ha="right" if rot else "center")
    plt.tight_layout()
    if filename:
        plt.savefig(fig_path(filename), dpi=110, bbox_inches="tight")
    plt.show()


# COMMAND ----------


# DBTITLE 1,Profiling-export helper (writes src/schemas/profiling/<source>.md)
def _repo_root():
    p = _os.path.abspath(_os.getcwd())
    for _ in range(12):
        if _os.path.isdir(_os.path.join(p, "src", "schemas")) and _os.path.isdir(
            _os.path.join(p, "databricks", "eda")
        ):
            return p
        if _os.path.dirname(p) == p:
            break
        p = _os.path.dirname(p)
    with contextlib.suppress(Exception):
        wp = (
            dbutils.notebook.entry_point.getDbutils()
            .notebook()
            .getContext()
            .notebookPath()
            .get()
        )
        i = wp.rfind("/databricks/eda/")
        if i > 0:
            for cand in (wp[:i], "/Workspace" + wp[:i]):
                if _os.path.isdir(_os.path.join(cand, "src", "schemas")):
                    return cand
    raise RuntimeError(
        "repo root not found -- run from <repo>/databricks/eda/<source>/"
    )


def _profiling_dir():
    d = _os.path.join(_repo_root(), "src", "schemas", "profiling")
    _os.makedirs(_os.path.join(d, "figures"), exist_ok=True)
    return d


def fig_path(name):
    return _os.path.join(_profiling_dir(), "figures", name)


def fmt_pairs(pairs, n=25):
    # Render (label, value) pairs as markdown list lines, capped at n with a
    # "... (N more)" tail so the profiling .md never carries a 1000-row dump.
    items = list(pairs)
    out = [f"- {lbl}: {val}" for lbl, val in items[:n]]
    if len(items) > n:
        out.append(f"- ... ({len(items) - n} more)")
    return "\n".join(out)


def write_profiling(source, notebook_key, section_title, blocks, figures=None):
    d = _profiling_dir()
    md = _os.path.join(d, source + ".md")
    lines = [f"<!-- BEGIN {source}:{notebook_key} -->", f"## {section_title}", ""]
    for heading, body in blocks:
        if body is None or str(body).strip() == "":
            continue
        lines += [f"### {heading}", "", str(body).rstrip(), ""]
    for cap, name in figures or []:
        if not _os.path.exists(_os.path.join(d, "figures", name)):
            print(f"  profiling export: skipping absent figure {name}")
            continue
        lines += [f"### Figure -- {cap}", "", f"![{cap}](figures/{name})", ""]
    lines.append(f"<!-- END {source}:{notebook_key} -->")
    block = "\n".join(lines)
    existing = ""
    if _os.path.exists(md):
        with open(md, encoding="utf-8") as fh:
            existing = fh.read()
    pat = _re.compile(
        r"<!-- BEGIN "
        + _re.escape(source)
        + r":([\w.\-]+) -->.*?<!-- END "
        + _re.escape(source)
        + r":\1 -->",
        _re.DOTALL,
    )
    kept = {mm.group(1): mm.group(0) for mm in pat.finditer(existing)}
    kept[notebook_key] = block
    intro = f"_Auto-generated by the Phase 3 EDA notebooks (`databricks/eda/{source}/`). One `## ` section per notebook; re-running a notebook replaces its own section, other sections are preserved._"
    header = f"# {source.upper()} EDA PROFILE\n\n{intro}\n\n"
    body = "\n\n".join(kept[k] for k in sorted(kept))
    out = header + body + "\n"
    tmp = md + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(out)
    _os.replace(tmp, md)
    print(f"profiling export -> {md}  ('{notebook_key}', {len(kept)} section(s))")


# COMMAND ----------

# DBTITLE 1,Validate profiling export path
REPO_ROOT = _repo_root()
PROFILING_DIR = _profiling_dir()

print(f"OK  repo root: {REPO_ROOT}")
print(f"OK  profiling directory: {PROFILING_DIR}")

# COMMAND ----------

# DBTITLE 1,Schema, row count, missingness, approx distinct, constant columns (one pass)
df = spark.table(TABLE)
COLS = df.columns
exprs = [F.count(F.lit(1)).alias("__rows")]
for c in COLS:
    miss = F.col(c).isNull() | (F.trim(F.col(c)) == "")
    exprs += [
        F.sum(miss.cast("long")).alias(c + "__m"),
        F.approx_count_distinct(c).alias(c + "__d"),
    ]
r = df.agg(*exprs).first().asDict()
total = r["__rows"]
constant_cols = [c for c in COLS if r[c + "__d"] <= 1]
print(f"rows={total}  columns={len(COLS)}  ->  {COLS}")
for c in COLS:
    print(
        f"  {c:<14} missing={r[c + '__m']:>8} rate={r[c + '__m'] / total:.4f} approx_distinct={r[c + '__d']}"
    )
print("constant columns:", constant_cols)
df.show(20, truncate=False)

# COMMAND ----------

# DBTITLE 1,Collect the full table (small) for row-level analysis
rows = df.select(*COLS).collect()
recs = [x.asDict() for x in rows]
full_row_dups = total - len({tuple(sorted(d.items())) for d in recs})
print("full-row duplicates:", full_row_dups)

by_type = {}
for d in recs:
    by_type.setdefault(d["lookup_type"], []).append(d)
type_rows = sorted(((lt, len(v)) for lt, v in by_type.items()), key=lambda p: -p[1])
print("rows per lookup_type:", type_rows)

# COMMAND ----------

# DBTITLE 1,lookup_id uniqueness, id range and contiguity per lookup_type
uniq = {}
for lt, v in by_type.items():
    ids = sorted(int(d["lookup_id"]) for d in v if d["lookup_id"] not in (None, ""))
    dup_ids = len(ids) - len(set(ids))
    gaps = sorted(set(range(ids[0], ids[-1] + 1)) - set(ids)) if ids else []
    uniq[lt] = {
        "n": len(ids),
        "min": ids[0] if ids else None,
        "max": ids[-1] if ids else None,
        "dup_ids": dup_ids,
        "gaps_in_range": len(gaps),
        "gap_examples": gaps[:20],
    }
    print(f"{lt}: {uniq[lt]}")

# COMMAND ----------

# DBTITLE 1,name_en / name_cn completeness, distinct names, placeholder tokens per type
PLACEHOLDERS = {"unknown", "other", "others", "n/a", "na", "null", "未知", "其他"}
name_missing = []
for lt, v in by_type.items():
    en_missing = sum(1 for d in v if not (d["name_en"] or "").strip())
    cn_missing = sum(1 for d in v if not (d["name_cn"] or "").strip())
    both = sum(
        1 for d in v if (d["name_en"] or "").strip() and (d["name_cn"] or "").strip()
    )
    ph = sum(
        1
        for d in v
        if (d["name_en"] or "").strip().lower() in PLACEHOLDERS
        or (d["name_cn"] or "").strip() in PLACEHOLDERS
    )
    name_missing.append((lt, en_missing, cn_missing, len(v)))
    print(
        f"{lt}: name_en_missing={en_missing} name_cn_missing={cn_missing} both_present={both} "
        f"placeholder_like={ph} distinct_en={len({d['name_en'] for d in v})} "
        f"distinct_cn={len({d['name_cn'] for d in v})}"
    )
both_present = sum(
    1 for d in recs if (d["name_en"] or "").strip() and (d["name_cn"] or "").strip()
)

# COMMAND ----------

# DBTITLE 1,Extra columns beyond the expected 4 (staging superset artefacts)
extra = [c for c in COLS if c not in {"lookup_type", "lookup_id", "name_en", "name_cn"}]
print("extra columns:", extra)
for c in extra:
    acc = {}
    for d in recs:
        acc.setdefault(d["lookup_type"], {})
        acc[d["lookup_type"]][d[c]] = acc[d["lookup_type"]].get(d[c], 0) + 1
    print(f"  {c}:", acc)

# COMMAND ----------

# DBTITLE 1,Figure -- rows per lookup_type + name missingness
barplot(
    type_rows,
    "iPinYou reference -- rows per lookup_type",
    "lookup_type",
    "rows",
    filename="ipinyou_reference_rows_per_lookup_type.png",
)
types = [n[0] for n in name_missing]
x = np.arange(len(types))
plt.figure(figsize=(9, 4))
plt.bar(
    x - 0.2,
    [n[1] / n[3] for n in name_missing],
    width=0.4,
    label="name_en missing rate",
)
plt.bar(
    x + 0.2,
    [n[2] / n[3] for n in name_missing],
    width=0.4,
    label="name_cn missing rate",
)
plt.xticks(x, types)
plt.legend()
plt.title("iPinYou reference -- name missingness by lookup_type")
plt.ylabel("rate")
plt.tight_layout()
plt.savefig(
    fig_path("ipinyou_reference_name_missingness_by_lookup_type.png"),
    dpi=110,
    bbox_inches="tight",
)
plt.show()

# COMMAND ----------

# DBTITLE 1,Findings
print("constant columns:", constant_cols)
print("rows per lookup_type:", type_rows)
print("lookup_id uniqueness / contiguity:", uniq)
print("rows with both names present:", both_present, "/", total)
print("full-row duplicates:", full_row_dups)

# COMMAND ----------

# DBTITLE 1,Export profiling findings -> src/schemas/profiling/ipinyou.md
_prof = ["| column | missing | rate | approx_distinct |", "|---|---|---|---|"]
for c in COLS:
    _prof.append(
        f"| {c} | {r[c + '__m']} | {r[c + '__m'] / total:.4f} | {r[c + '__d']} |"
    )
_prof += [
    "",
    (
        f"Rows: {total}. Merged lookup discriminated by `lookup_type`. "
        f"Constant columns: {constant_cols or 'none'}. "
        f"Extra columns beyond (lookup_type, lookup_id, name_en, name_cn): {extra or 'none'}."
    ),
]

_dq = [
    f"Full-row duplicates: {full_row_dups}.",
    "",
    "Per lookup_type -- lookup_id uniqueness and contiguity:",
    "",
    "| lookup_type | n | min id | max id | duplicate ids | gaps in range |",
    "|---|---|---|---|---|---|",
]
for lt, u in uniq.items():
    _dq.append(
        f"| {lt} | {u['n']} | {u['min']} | {u['max']} | {u['dup_ids']} | {u['gaps_in_range']} |"
    )

_entities = ["Rows per lookup_type:", "", "| lookup_type | rows |", "|---|---|"]
for lt, n in type_rows:
    _entities.append(f"| {lt} | {n} |")

_coverage = [
    "Name completeness per lookup_type:",
    "",
    "| lookup_type | name_en missing | name_cn missing | rows |",
    "|---|---|---|---|",
]
for lt, en_m, cn_m, n in name_missing:
    _coverage.append(f"| {lt} | {en_m} | {cn_m} | {n} |")
_coverage += ["", f"Rows with both names present: {both_present} / {total}."]

_findings = []
if constant_cols:
    _findings.append(f"- Constant columns: {constant_cols}.")
if full_row_dups:
    _findings.append(f"- {full_row_dups} full-row duplicates.")
_dup_id_types = {lt: u["dup_ids"] for lt, u in uniq.items() if u["dup_ids"]}
if _dup_id_types:
    _findings.append(
        f"- lookup_id is not unique within lookup_type for: {_dup_id_types}."
    )
_gap_types = {lt: u["gaps_in_range"] for lt, u in uniq.items() if u["gaps_in_range"]}
if _gap_types:
    _findings.append(f"- lookup_id ranges are non-contiguous (gaps) for: {_gap_types}.")
_name_gap = {lt: (en_m, cn_m) for lt, en_m, cn_m, n in name_missing if en_m or cn_m}
if _name_gap:
    _findings.append(f"- Missing names by type (en, cn): {_name_gap}.")
if extra:
    _findings.append(f"- Staging superset artefact columns present: {extra}.")
_findings_md = "\n".join(_findings) if _findings else "Reference table is clean."

_silver = []
if constant_cols or extra:
    _silver.append(
        f"- Drop constant/artefact columns: {sorted(set(constant_cols) | set(extra))}."
    )
_silver.append(
    "- Split the merged lookup into one dimension per lookup_type "
    "(city, region, user_profile_tag) keyed on lookup_id."
)
if _dup_id_types:
    _silver.append(
        "- De-duplicate lookup_id within each type before using it as a dimension key."
    )
if _name_gap:
    _silver.append(
        "- Coalesce name_en/name_cn and keep an 'unknown' member for unmatched foreign keys."
    )

write_profiling(
    SOURCE,
    NB_KEY,
    SECTION_TITLE,
    [
        ("Profile", "\n".join(_prof)),
        ("Data Quality", "\n".join(_dq)),
        ("Entities / Keys", "\n".join(_entities)),
        ("Coverage", "\n".join(_coverage)),
        ("EDA Findings", _findings_md),
        ("Silver Implications", "\n".join(_silver)),
    ],
    figures=[
        (
            "iPinYou reference -- rows per lookup_type",
            "ipinyou_reference_rows_per_lookup_type.png",
        ),
        (
            "iPinYou reference -- name missingness by lookup_type",
            "ipinyou_reference_name_missingness_by_lookup_type.png",
        ),
    ],
)
