# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# MAGIC %md
# MAGIC # EDA -- IPINYOU RELATIONSHIPS AND FINDINGS
# MAGIC
# MAGIC **Energy Commerce and Retail Media Analytics Platform**
# MAGIC **Author:** Sharique Mohammad
# MAGIC **Date:** August 2026
# MAGIC
# MAGIC **Purpose:** Cross-table checks across the 3 iPinYou Bronze tables --
# MAGIC training vs leaderboard schema/overlap, region & city referential
# MAGIC integrity against ipinyou_reference, user_tags vs the tag lookup -- and
# MAGIC a findings summary for src/schemas/profiling/ipinyou.md.

# COMMAND ----------

# DBTITLE 1,Imports
import contextlib
import os as _os
import re as _re

import matplotlib.pyplot as plt
import numpy as np
from pyspark.sql import functions as F

# COMMAND ----------

# DBTITLE 1,Configuration
CATALOG = "energy_commerce_retail_media"
BRONZE_SCHEMA = "bronze"
SOURCE = "ipinyou"
NB_KEY = "03_relationships_and_findings"
SECTION_TITLE = "Cross-table relationships (training, leaderboard, reference)"
training = spark.table(f"{CATALOG}.{BRONZE_SCHEMA}.ipinyou_training")
leaderboard = spark.table(f"{CATALOG}.{BRONZE_SCHEMA}.ipinyou_leaderboard")
reference = spark.table(f"{CATALOG}.{BRONZE_SCHEMA}.ipinyou_reference")
FACTS = {"training": training, "leaderboard": leaderboard}

# COMMAND ----------


# DBTITLE 1,Helper
def barplot(pairs, title, xlabel, ylabel="count", rot=0, filename=None):
    plt.figure(figsize=(9, 4))
    plt.bar([str(p[0]) for p in pairs], [p[1] for p in pairs])
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.xticks(rotation=rot, ha="right" if rot else "center")
    plt.tight_layout()
    if filename:
        plt.savefig(fig_path(filename), dpi=110, bbox_inches="tight")
    plt.show()


# COMMAND ----------


# DBTITLE 1,Profiling-export helper (writes src/schemas/profiling/<source>.md)
def _repo_root():
    p = _os.path.abspath(_os.getcwd())
    for _ in range(12):
        if _os.path.isdir(_os.path.join(p, "src", "schemas")) and _os.path.isdir(
            _os.path.join(p, "databricks", "eda")
        ):
            return p
        if _os.path.dirname(p) == p:
            break
        p = _os.path.dirname(p)
    with contextlib.suppress(Exception):
        wp = (
            dbutils.notebook.entry_point.getDbutils()
            .notebook()
            .getContext()
            .notebookPath()
            .get()
        )
        i = wp.rfind("/databricks/eda/")
        if i > 0:
            for cand in (wp[:i], "/Workspace" + wp[:i]):
                if _os.path.isdir(_os.path.join(cand, "src", "schemas")):
                    return cand
    raise RuntimeError(
        "repo root not found -- run from <repo>/databricks/eda/<source>/"
    )


def _profiling_dir():
    d = _os.path.join(_repo_root(), "src", "schemas", "profiling")
    _os.makedirs(_os.path.join(d, "figures"), exist_ok=True)
    return d


def fig_path(name):
    return _os.path.join(_profiling_dir(), "figures", name)


def fmt_pairs(pairs, n=25):
    # Render (label, value) pairs as markdown list lines, capped at n with a
    # "... (N more)" tail so the profiling .md never carries a 1000-row dump.
    items = list(pairs)
    out = [f"- {lbl}: {val}" for lbl, val in items[:n]]
    if len(items) > n:
        out.append(f"- ... ({len(items) - n} more)")
    return "\n".join(out)


def write_profiling(source, notebook_key, section_title, blocks, figures=None):
    d = _profiling_dir()
    md = _os.path.join(d, source + ".md")
    lines = [f"<!-- BEGIN {source}:{notebook_key} -->", f"## {section_title}", ""]
    for heading, body in blocks:
        if body is None or str(body).strip() == "":
            continue
        lines += [f"### {heading}", "", str(body).rstrip(), ""]
    for cap, name in figures or []:
        if not _os.path.exists(_os.path.join(d, "figures", name)):
            print(f"  profiling export: skipping absent figure {name}")
            continue
        lines += [f"### Figure -- {cap}", "", f"![{cap}](figures/{name})", ""]
    lines.append(f"<!-- END {source}:{notebook_key} -->")
    block = "\n".join(lines)
    existing = ""
    if _os.path.exists(md):
        with open(md, encoding="utf-8") as fh:
            existing = fh.read()
    pat = _re.compile(
        r"<!-- BEGIN "
        + _re.escape(source)
        + r":([\w.\-]+) -->.*?<!-- END "
        + _re.escape(source)
        + r":\1 -->",
        _re.DOTALL,
    )
    kept = {mm.group(1): mm.group(0) for mm in pat.finditer(existing)}
    kept[notebook_key] = block
    intro = f"_Auto-generated by the Phase 3 EDA notebooks (`databricks/eda/{source}/`). One `## ` section per notebook; re-running a notebook replaces its own section, other sections are preserved._"
    header = f"# {source.upper()} EDA PROFILE\n\n{intro}\n\n"
    body = "\n\n".join(kept[k] for k in sorted(kept))
    out = header + body + "\n"
    tmp = md + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(out)
    _os.replace(tmp, md)
    print(f"profiling export -> {md}  ('{notebook_key}', {len(kept)} section(s))")


# COMMAND ----------

# DBTITLE 1,Validate profiling export path
REPO_ROOT = _repo_root()
PROFILING_DIR = _profiling_dir()

print(f"OK  repo root: {REPO_ROOT}")
print(f"OK  profiling directory: {PROFILING_DIR}")

# COMMAND ----------

# DBTITLE 1,Schema difference
t_cols, l_cols = set(training.columns), set(leaderboard.columns)
print("training-only columns  :", sorted(t_cols - l_cols))
print("leaderboard-only columns:", sorted(l_cols - t_cols))
print("shared columns          :", sorted(t_cols & l_cols))

# COMMAND ----------

# DBTITLE 1,Reference id sets by lookup_type (collect small table once)
ref_ids = {"region": set(), "city": set(), "tag": set()}
for x in reference.select(
    "lookup_type", F.col("lookup_id").cast("string").alias("id")
).collect():
    if x["lookup_type"] in ref_ids and x["id"] is not None:
        ref_ids[x["lookup_type"]].add(x["id"])
print({k: len(v) for k, v in ref_ids.items()})

# COMMAND ----------

# DBTITLE 1,(season, bid_id) key overlap -- exact (key relationship check)
t_keys = training.select("season", "bid_id").distinct()
l_keys = leaderboard.select("season", "bid_id").distinct()
t_ct, l_ct = t_keys.count(), l_keys.count()
overlap = t_keys.join(l_keys, on=["season", "bid_id"], how="inner").count()
seasons = {
    n: sorted(x["season"] for x in df.select("season").distinct().collect())
    for n, df in FACTS.items()
}
print(f"training keys={t_ct}  leaderboard keys={l_ct}  overlap={overlap}")
print("seasons:", seasons)

# COMMAND ----------

# DBTITLE 1,Entity value sets per fact (collect_set -- one pass per fact)
entity_sets = {}
for name, df in FACTS.items():
    row = df.agg(
        F.collect_set(F.col("region").cast("string")).alias("region"),
        F.collect_set(F.col("city").cast("string")).alias("city"),
        F.collect_set(F.col("advertiser_id").cast("string")).alias("advertiser_id"),
    ).first()
    tags = (
        df.select(F.explode(F.split(F.col("user_tags"), r"[,;\s]+")).alias("t"))
        .where(F.trim(F.col("t")) != "")
        .agg(F.collect_set(F.trim(F.col("t"))).alias("tag"))
        .first()["tag"]
    )
    entity_sets[name] = {
        "region": set(row["region"]),
        "city": set(row["city"]),
        "advertiser_id": set(row["advertiser_id"]),
        "tag": set(tags or []),
    }
    print(name, {k: len(v) for k, v in entity_sets[name].items()})

# COMMAND ----------

# DBTITLE 1,Referential integrity: distinct-id coverage vs ipinyou_reference (Python set math)
fk = {}
for name in FACTS:
    fk[name] = {}
    for dim, ref_key in (("region", "region"), ("city", "city"), ("tag", "tag")):
        used = entity_sets[name][dim]
        unmatched = used - ref_ids[ref_key]
        fk[name][f"{dim}_used"] = len(used)
        fk[name][f"{dim}_unmatched"] = len(unmatched)
        print(
            f"{name}.{dim}: used={len(used)} unmatched={len(unmatched)} e.g. {sorted(unmatched)[:20]}"
        )

# COMMAND ----------

# DBTITLE 1,Row-level FK coverage: share of fact ROWS matching a reference id (one pass per fact)
row_cov = {}
for name, df in FACTS.items():
    region_ok = F.col("region").cast("string").isin(list(ref_ids["region"]))
    city_ok = F.col("city").cast("string").isin(list(ref_ids["city"]))
    a = (
        df.agg(
            F.count(F.lit(1)).alias("rows"),
            F.sum(region_ok.cast("long")).alias("region_match"),
            F.sum(city_ok.cast("long")).alias("city_match"),
        )
        .first()
        .asDict()
    )
    row_cov[name] = {
        "rows": a["rows"],
        "region_match_rate": round(a["region_match"] / a["rows"], 4),
        "city_match_rate": round(a["city_match"] / a["rows"], 4),
    }
    print(f"{name}: {row_cov[name]}")

# COMMAND ----------

# DBTITLE 1,Join cardinality -- training.region / training.city -> reference (expect N:1)
for dim in ("region", "city"):
    s = (
        training.groupBy(F.col(dim).cast("string").alias(dim))
        .count()
        .agg(
            F.min("count").alias("min"),
            F.max("count").alias("max"),
            F.avg("count").alias("avg"),
            F.count(F.lit(1)).alias("distinct_values"),
        )
        .first()
        .asDict()
    )
    print(
        f"training.{dim} -> ipinyou_reference.{dim}: {'N:1' if s['max'] > 1 else '1:1'}  {s}"
    )

# COMMAND ----------

# DBTITLE 1,Advertiser overlap training vs leaderboard (Python set math)
t_adv, l_adv = (
    entity_sets["training"]["advertiser_id"],
    entity_sets["leaderboard"]["advertiser_id"],
)
adv_overlap = len(t_adv & l_adv)
print(
    f"training advertisers={len(t_adv)}  leaderboard advertisers={len(l_adv)}  shared={adv_overlap}"
)
print("training-only:", sorted(t_adv - l_adv)[:20])
print("leaderboard-only:", sorted(l_adv - t_adv)[:20])

# COMMAND ----------

# DBTITLE 1,Verdict -- union training + leaderboard?
print("training-only columns   :", sorted(t_cols - l_cols))
print("leaderboard-only columns :", sorted(l_cols - t_cols))
print(f"(season, bid_id) overlap : {overlap} of {t_ct} / {l_ct}")
print(f"advertiser overlap       : {adv_overlap} of {len(t_adv)} / {len(l_adv)}")
print("seasons:", seasons)
print(
    "=> shared 20+ columns and the same event grain, different label columns "
    "(event_type vs has_conversion / related_clicks_count), near-zero key overlap "
    "-> two separate facts sharing conformed dimensions."
)

# COMMAND ----------

# DBTITLE 1,Figure -- key overlap + FK unmatched rates
barplot(
    [("training keys", t_ct), ("leaderboard keys", l_ct), ("overlap", overlap)],
    "iPinYou -- (season, bid_id) key overlap",
    "",
    "keys",
    rot=20,
    filename="ipinyou_season_bid_id_key_overlap.png",
)
dims = ["region", "city", "tag"]
x = np.arange(len(dims))
plt.figure(figsize=(10, 4))
for i, name in enumerate(FACTS):
    plt.bar(
        x + i * 0.35,
        [fk[name][f"{d}_unmatched"] / max(fk[name][f"{d}_used"], 1) for d in dims],
        width=0.35,
        label=name,
    )
plt.xticks(x + 0.17, dims)
plt.legend()
plt.title("iPinYou -- share of id values not found in ipinyou_reference")
plt.ylabel("unmatched rate")
plt.tight_layout()
plt.savefig(fig_path("ipinyou_fk_unmatched_rate.png"), dpi=110, bbox_inches="tight")
plt.show()

# COMMAND ----------

# DBTITLE 1,Findings
print("schema delta training-only :", sorted(t_cols - l_cols))
print("schema delta leaderboard-only:", sorted(l_cols - t_cols))
print("(season, bid_id) overlap    :", overlap)
print("advertiser overlap          :", adv_overlap, "of", len(t_adv), "/", len(l_adv))
print("distinct-id FK              :", fk)
print("row-level FK match rate     :", row_cov)

# COMMAND ----------

# DBTITLE 1,Export profiling findings -> src/schemas/profiling/ipinyou.md
_entities = [
    (
        f"Schema delta: training-only columns = {sorted(t_cols - l_cols)}; "
        f"leaderboard-only columns = {sorted(l_cols - t_cols)}; "
        f"shared columns = {len(t_cols & l_cols)}."
    ),
    f"Seasons: {seasons}.",
    f"Reference id sets: { {k: len(v) for k, v in ref_ids.items()} }.",
]

_rel = [
    f"(season, bid_id) keys: training={t_ct}, leaderboard={l_ct}, inner overlap={overlap}.",
    f"Advertiser overlap: training={len(t_adv)}, leaderboard={len(l_adv)}, shared={adv_overlap}.",
    "",
    "Referential integrity vs ipinyou_reference (distinct id values):",
    "",
    "| fact | dim | used | unmatched |",
    "|---|---|---|---|",
]
for name in FACTS:
    for d in ("region", "city", "tag"):
        _rel.append(
            f"| {name} | {d} | {fk[name][f'{d}_used']} | {fk[name][f'{d}_unmatched']} |"
        )
_rel += ["", "Row-level FK match rate:", ""]
for name, v in row_cov.items():
    _rel.append(
        f"- {name}: rows={v['rows']}, region_match_rate={v['region_match_rate']}, "
        f"city_match_rate={v['city_match_rate']}"
    )

_verdict = (
    "Training and leaderboard share 20+ columns and the same event grain but carry "
    "different label columns (event_type vs has_conversion / related_clicks_count) and "
    "have near-zero (season, bid_id) key overlap -> model as two separate facts sharing "
    "conformed dimensions, not a union."
)

_findings = []
if overlap == 0:
    _findings.append(
        "- training and leaderboard (season, bid_id) keys do not overlap at all."
    )
for name in FACTS:
    for d in ("region", "city", "tag"):
        if fk[name][f"{d}_unmatched"]:
            _findings.append(
                f"- {name}.{d}: {fk[name][f'{d}_unmatched']} id values are absent from ipinyou_reference."
            )
for name, v in row_cov.items():
    if v["region_match_rate"] < 1 or v["city_match_rate"] < 1:
        _findings.append(
            f"- {name}: not all rows resolve to a reference region/city "
            f"(region {v['region_match_rate']}, city {v['city_match_rate']})."
        )
_findings_md = (
    "\n".join(_findings) if _findings else "All FK relationships resolve cleanly."
)

_silver = [
    "- Load training and leaderboard as separate fact tables sharing conformed dimensions.",
    "- Build region/city/tag dimensions from ipinyou_reference; keep an 'unknown' member.",
]
if any(fk[n][f"{d}_unmatched"] for n in FACTS for d in ("region", "city", "tag")):
    _silver.append(
        "- Left-join facts to dimensions and route unmatched ids to the 'unknown' member "
        "rather than dropping rows."
    )

write_profiling(
    SOURCE,
    NB_KEY,
    SECTION_TITLE,
    [
        ("Entities / Keys", "\n".join(_entities)),
        ("Relationships", "\n".join(_rel)),
        ("EDA Findings", _findings_md + "\n\n" + _verdict),
        ("Silver Implications", "\n".join(_silver)),
    ],
    figures=[
        (
            "iPinYou -- (season, bid_id) key overlap",
            "ipinyou_season_bid_id_key_overlap.png",
        ),
        (
            "iPinYou -- share of id values not found in ipinyou_reference",
            "ipinyou_fk_unmatched_rate.png",
        ),
    ],
)
